/*
 * Copyright (c) 2026 Sapporo_ningyo
 *
 * Licensed under Apache License 2.0; see LICENSE and NOTICE.
 */

#pragma once

#include <map>
#include <string>
#include <string_view>

enum class Language { Ja, En, Zh };

struct Translation {
    std::map<std::string, std::string, std::less<>> en;
    std::map<std::string, std::string, std::less<>> zh;
    std::map<std::string, std::string, std::less<>> ja;

    Translation() {
        en = {
            {"menu.import_submap", "Import Submap..."},
            {"menu.new_submap", "New Submap..."},
            {"dialog.create_include_file", "Create Submap File"},
            {"status.edit.include_create_failed", "Unable to create the submap file."},
            {"frame.sections", "Section List"},
            {"frame.section_begins", "Section Begin Positions"},
            {"frame.section_speed_limits", "Section Speed Limits"},
            {"frame.variables", "Variable List"},
            {"frame.scenario_file", "Scenario File"},
            {"menu.map_info.sections", "Sections"},
            {"menu.map_info.variables", "Variables"},
            {"menu.map_info.scenario_file", "Scenario File"},
            {"menu.locate_in_section_list", "Locate in Section List"},
            {"chk.section_markers", "Section Markers"},
            {"label.source_path", "Source path"},
            {"label.enable_time", "Enable time"},
            {"column.variable", "Variable"},
            {"column.value", "Value"},
            {"scene.route_info.speed_limit", "Speedlimit:"},
            {"scene.route_info.signal", "Signal:"},
            {"dialog.coordinate_offset_discard_title", "Remove Coordinate Offsets"},
            {"dialog.coordinate_offset_discard_message", "All coordinate offsets for this scenery object will be discarded. Continue?"},
            {"label.repeater_end_source", "End source:"}, {"value.none", "None"}, {"value.own_track", "(owntrack)"},
            {"value.tilt.always_level", "Always level"}, {"value.tilt.follow_gradient", "Follow gradient"}, {"value.tilt.follow_cant", "Follow cant"}, {"value.tilt.follow_gradient_and_cant", "Follow gradient and cant"},
            {"value.door.open_left", "Open left-side doors"}, {"value.door.do_not_open", "Do not open doors"}, {"value.door.open_right", "Open right-side doors"},
            {"status.transition_unpaired", "This BeginTransition has no corresponding Begin/End and cannot be edited or deleted."},
            {"label.repeater_structure_keys", "Structure keys"},
            {"label.section_parameters", "Parameters"},
            {"status.repeater_multiple_begins", "This Repeater has multiple Begin statements."},
            {"button.add_repeater_end_position", "Add End Position"},
            {"button.insert_repeater_change_point", "Insert Change Point"},
            {"status.map_loading", "Loading map..."}, {"status.map_loaded", "Map loaded"}, {"status.map_load_failed", "Map load failed"},
            {"status.scene_preview_loading", "Loading 3D scene preview..."}, {"status.scene_preview_loaded", "3D scene preview loaded"}, {"status.scene_preview_failed", "3D scene preview failed"}, {"status.scene_preview_stopped", "3D scene preview stopped"},
            {"status.no_errors_warnings", "No errors or warnings"}, {"frame.errors_warnings", "Errors and Warnings"},
            {"scene.route_info.straight", "Straight"}, {"scene.route_info.interpolate_unsupported", "interpolate(unsupported)"}, {"scene.route_info.next_station", "Next sta. :"}, {"scene.route_info.no_station_ahead", "No station ahead"},
            {"dialog.distance_expression_message", "Edit the distance source expression manually?"},
            {"dialog.signal_full_form_convert_title", "Convert Signal.Put"}, {"dialog.signal_full_form_convert_message", "This signal uses the short Signal.Put form. Convert it to the full form before editing Z, rotation, tilt, or span?"},
            {"dialog.structure_z_rebase_title", "Adjust Distance"}, {"dialog.structure_z_rebase_message", "The current model's Z-axis offset exceeds 5 m. Adjust the distance?"},
            {"app.title", "komapedit"},
            {"menu.map_info.other_trains", "Other Train"},
            {"frame.other_trains", "Other Train List"},
            {"frame.other_train_definitions", "Definitions"},
            {"frame.other_train_stops", "Stop Points"},
            {"frame.structure_put", "Put"},
            {"frame.structure_put_between", "PutBetween"},
            {"menu.locate_in_other_train_stop_list", "Locate in Other Train Stop Point List"},
            {"frame.map_sounds", "Map Sound List"},
            {"frame.map_sound_3d", "Fixed Sound Source List"},
            {"button.map_sound_list", "Map Sound List"},
            {"button.map_sound_3d_list", "Map 3D Sound List"},
            {"chk.map_sound_markers", "Sound Play Positions"},
            {"chk.map_sound_3d_markers", "Fixed Sound Positions"},
            {"menu.locate_in_map_sound_list", "Locate in Map Sound List"},
            {"menu.locate_in_map_sound_3d_list", "Locate in Map 3D Sound List"},
            {"frame.rolling_noises", "Rolling Noise Change Point List"},
            {"chk.rolling_noise_markers", "Rolling Noise Change Points"},
            {"menu.locate_in_rolling_noise_list", "Locate in Rolling Noise Change Point List"},
            {"frame.flange_noises", "Flange Noise Change Point List"},
            {"chk.flange_noise_markers", "Flange Noise Change Points"},
            {"menu.locate_in_flange_noise_list", "Locate in Flange Noise Change Point List"},
            {"frame.joint_noises", "Joint Noise Play Point List"},
            {"chk.joint_noise_markers", "Joint Noise Play Points"},
            {"menu.locate_in_joint_noise_list", "Locate in Joint Noise Play Point List"},
            {"frame.backgrounds", "Background Change Point List"},
            {"chk.background_markers", "Background Change Points"},
            {"menu.locate_in_background_list", "Locate in Background Change Point List"},
            {"menu.file", "File"}, {"menu.options", "Options"}, {"menu.map_info", "Map Info List"}, {"menu.view_2d", "2D View"}, {"menu.lang", "Language"}, {"menu.help", "Help"},
            {"menu.map_info.othertracks", "Other Tracks"}, {"menu.map_info.station", "Station List"}, {"menu.map_info.signal_aspects", "Signal Aspect"}, {"menu.map_info.signals", "Map Signal"}, {"menu.map_info.beacons", "Beacon"},
            {"menu.map_info.structures", "Map Structure"}, {"menu.map_info.structures_put_between", "Map Structure (PutBetween)"}, {"menu.map_info.structure_models", "Structure Model"}, {"menu.map_info.sound_files", "Sound File"}, {"menu.map_info.sound_3d_files", "3D Sound File"}, {"menu.map_info.map_sounds", "Map Sound"},
            {"menu.map_info.map_sound_3d", "Map 3D Sound"}, {"menu.map_info.repeaters", "Repeater"}, {"menu.map_info.irregularities", "Track Irregularity"}, {"menu.map_info.rolling_noises", "Rolling Noise Change Point"}, {"menu.map_info.flange_noises", "Flange Noise Change Point"},
            {"menu.map_info.joint_noises", "Joint Noise Play Point"}, {"menu.map_info.backgrounds", "Background Change Point"}, {"menu.map_info.adhesions", "Adhesion Change Point"}, {"menu.map_info.speed_limits", "Speed Limit Point"}, {"menu.map_info.cab_illuminance", "Cab Illuminance Change Point"}, {"menu.map_info.fogs", "Fog Change Point"}, {"menu.map_info.legacy_fogs", "Legacy Fog Change Point"}, {"menu.map_info.lighting", "Lighting"}, {"menu.map_info.draw_distances", "Draw Distance Change Point"},
            {"menu.open", "Open..."}, {"menu.recent_maps", "Recent Maps"}, {"menu.none", "None"}, {"menu.clear_recent_maps", "Clear List"}, {"menu.reload", "Reload"}, {"menu.export_csv", "Export CSV..."}, {"menu.exit", "Exit"},
            {"menu.controlpoints", "Control Points..."}, {"menu.plotlimit", "Plot Range..."}, {"menu.ui_settings", "UI Settings..."}, {"menu.canvas_2d_settings", "2D Canvas Settings"}, {"menu.canvas_element_sizes", "Canvas Element Sizes"}, {"menu.canvas_3d_settings", "3D Canvas Settings"}, {"menu.about", "About"},
            {"menu.online_docs", "Online Documentation"}, {"menu.report_bugs", "Report Bugs"}, {"menu.open_in_explorer", "Open in File Explorer"}, {"menu.select_file", "Select File"}, {"menu.preview_text", "Preview Text"}, {"menu.unreference_include", "Unlink Include"}, {"menu.change_include_file", "Change Included File..."}, {"menu.change_file", "Change File..."}, {"menu.locate_on_plan", "Locate on Plan"}, {"menu.locate_in_scene_preview", "Locate in 3D Scene Preview"}, {"menu.locate_in_structure_list", "Locate in Map Structure List"}, {"menu.locate_in_structure_put_between_list", "Locate in Map Structure List (PutBetween)"}, {"menu.locate_in_repeater_list", "Locate in Repeater List"}, {"menu.repeater_delete_all", "Delete All"}, {"menu.repeater_delete_change_point", "Delete Change Point"}, {"menu.repeater_trim_to_change_point", "Trim to Change Point"}, {"menu.repeater_start_from_change_point", "Start from Change Point"}, {"menu.jump_to_repeater_start_position", "Jump to Start Position"}, {"menu.jump_to_repeater_end_or_change_position", "Jump to End/Change Position"}, {"menu.locate_in_signal_list", "Locate in Map Signal List"}, {"menu.locate_in_beacon_list", "Locate in Beacon List"}, {"menu.locate_in_irregularity_list", "Locate in Track Irregularity List"}, {"menu.locate_in_adhesion_list", "Locate in Adhesion Change Point List"}, {"menu.locate_in_cab_illuminance_list", "Locate in Cab Illuminance Change Point List"}, {"menu.locate_in_fog_list", "Locate in Fog Change Point List"}, {"menu.locate_in_legacy_fog_list", "Locate in Legacy Fog Change Point List"}, {"menu.locate_in_draw_distance_list", "Locate in Draw Distance Change Point List"}, {"menu.locate_in_speed_limit_list", "Locate in Speed Limit Point List"},
            {"menu.view_3d", "3D View"}, {"menu.structure_model_preview", "Structure Model Preview"}, {"menu.scene_preview", "3D Scene Preview"}, {"menu.preview_model", "Preview Model"}, {"menu.switch_signal_aspect", "Switch Signal Aspect"}, {"menu.find_in_structure_models", "Find in Structure Model List"}, {"menu.find_in_signal_aspects", "Find in Signal Aspect List"}, {"menu.find_in_sound_files", "Find in Sound File List"}, {"menu.find_in_sound_3d_files", "Find in 3D Sound File List"},
            {"menu.use_this_model", "Use This Model"}, {"menu.use_this_sound", "Use This Sound"},
            {"button.open", "Open"}, {"button.reload", "Reload"}, {"button.reload_geometry", "Reload Track Geometry"}, {"button.reload_scene_models", "Reload (Models)"}, {"button.export_csv", "Export CSV"},
            {"button.structure_list", "Map Structure List"}, {"button.repeater_list", "Repeater List"},
            {"button.apply", "Apply"}, {"button.apply_jump_to_edit", "Apply and Edit"}, {"button.new", "New"}, {"button.reset", "Reset"}, {"button.revert", "Revert"}, {"button.save", "Save"}, {"button.delete", "Delete"}, {"button.ok", "OK"}, {"button.cancel", "Cancel"}, {"button.clear", "Clear"}, {"button.copy", "Copy"}, {"button.close", "Close"}, {"button.previous", "Previous"}, {"button.next", "Next"}, {"button.confirm_reuse", "Reuse Anyway"}, {"button.manual_select", "Select Manually"},
            {"button.confirm_and_load", "Confirm and Load"},
            {"button.add_coordinate_offsets", "Add Coordinate Offsets"}, {"button.remove_coordinate_offsets", "Remove Coordinate Offsets"},
            {"button.add_map_element", "Add Map Element"}, {"menu.add_map_element_at_current_mileage", "Add Map Element at Current Mileage"}, {"dialog.new_element_wizard", "New Map Element Wizard"}, {"label.new_element_target_file", "Target source file"}, {"label.transition_start", "Transition start distance"},
            {"menu.new_file", "New..."}, {"dialog.new_file_wizard", "New File Wizard"}, {"new_file.category.presets", "Presets"}, {"new_file.category.map", "Map"}, {"new_file.category.resource_lists", "Map Resource Lists"},
            {"new_file.usage.map", "Create a blank BveTs Map 2.02 source file."}, {"new_file.usage.structure", "Create a blank Structure List file for map structures."}, {"new_file.usage.signal", "Create a blank Signal Aspects List file for signal definitions."}, {"new_file.usage.sound", "Create a blank Sound List file for train and ambient sounds."}, {"new_file.usage.sound3d", "Create a blank Sound List file for three-dimensional sounds."}, {"new_file.usage.station", "Create a blank Station List file for station definitions."},
            {"label.new_file_name", "File name"}, {"label.new_file_directory", "File path"}, {"label.new_file_reference", "Reference in"}, {"button.select_directory", "Select Directory"}, {"button.confirm", "Confirm"}, {"dialog.select_export_folder", "Select export folder"}, {"dialog.select_new_file_directory", "Select file directory"},
            {"status.new_file.invalid_path", "Enter a valid file name and existing directory."}, {"status.new_file.create_failed", "Could not create the new file."}, {"status.new_file.created", "Created a new file."}, {"status.new_file.reference_requires_edit", "Referencing the file requires Edit Mode."}, {"status.new_file.resource_list_already_loaded", "This resource list type is already loaded."}, {"status.new_file.reference_failed", "The file was created, but its reference could not be staged."},
            {"button.import_file", "Import File"}, {"button.new_or_import_file", "New or Import File"}, {"button.add_row", "Add Row"},
            {"resource_list.name.station", "Station List"}, {"resource_list.name.structure", "Structure Model List"}, {"resource_list.name.signal", "Signal Aspect List"}, {"resource_list.name.sound", "Sound File List"}, {"resource_list.name.sound3d", "Fixed Sound Source List"},
            {"status.new_file.reused", "Reused the existing file."}, {"status.new_file.resource_list_already_present", "The current map already has {resource_list}. To replace it, right-click Source path at the top of the corresponding list."},
            {"new_element.usage.structure.put", "Place a Structure instance on the track at the given position."},
            {"new_element.usage.structure.put0", "Place a Structure without coordinate offset; only tilt and span are set."},
            {"new_element.usage.repeater.begin", "Add Repeater.Begin, Repeater.End, or both; Begin uses coordinate offsets."},
            {"new_element.usage.repeater.begin0", "Add Repeater.Begin0, Repeater.End, or both; Begin0 has no coordinate offsets."},
            {"chk.new_element_repeater_add_begin", "Add Begin"}, {"chk.new_element_repeater_add_end", "Add End"}, {"chk.new_element_include_parameter", "Include argument"},
            {"new_element.usage.curve", "Add a supported Curve start, end, or both."},
            {"new_element.usage.gradient", "Add a supported Gradient start, end, or both."},
            {"chk.new_element_add_start", "Add start position"}, {"chk.new_element_add_end", "Add end position"},
            {"chk.new_element_own_track_add_transition", "Add transition start"}, {"chk.new_element_add_parameter", "Add this argument"},
            {"new_element.usage.structure.put_between", "Place a Structure between two tracks and deform it to their separation."},
            {"new_element.usage.station.put", "Set a train stopping position at the given distance."},
            {"new_element.usage.signal.put", "Place a signal at the given position and section."},
            {"new_element.usage.speedlimit.begin", "Start a speed limit at the given distance and speed."},
            {"new_element.usage.speedlimit.end", "End a speed limit at the given distance."},
            {"new_element.usage.section.begin", "Start a new block section using the listed signal indices."},
            {"new_element.usage.section.beginnew", "Legacy alias for Section.Begin: start a new block section using the listed signal indices."},
            {"new_element.usage.section.setspeedlimit", "Set the permitted speeds for signal aspects at the given distance."},
            {"new_element.usage.section.signal_speedlimit", "Legacy alias for Section.SetSpeedLimit: set the permitted speeds for signal aspects at the given distance."},
            {"new_element.usage.irregularity.change", "Set track irregularity from the given distance onward."},
            {"new_element.usage.other_track.position", "Set the other-track position at the current distance (equivalent to X/Y interpolation)."},
            {"new_element.usage.other_track.x_interpolate", "Set the other-track X position at the current distance and interpolate from the preceding X point."},
            {"new_element.usage.other_track.y_interpolate", "Set the other-track Y position at the current distance and interpolate from the preceding Y point."},
            {"new_element.usage.other_track.cant_set_gauge", "Set the other-track gauge from the current distance onward, for converting cant to angle."},
            {"new_element.usage.other_track.cant_set_center", "Set the other-track cant rotation center from the current distance onward."},
            {"new_element.usage.other_track.cant_set_function", "Set the other-track cant-transition function from the current distance onward."},
            {"new_element.usage.other_track.cant_begin_transition", "Start an other-track cant transition at the current distance."},
            {"new_element.usage.other_track.cant_begin", "End the cant transition and begin constant cant at the current distance."},
            {"new_element.usage.other_track.cant_end", "End the other-track cant at the current distance."},
            {"new_element.usage.other_track.cant_interpolate", "Set other-track cant at the current distance and interpolate from the preceding cant point."},
            {"new_element.usage.beacon.put", "Define a beacon transmission event at the given distance."},
            {"new_element.usage.map_sound.play", "Play a sound once when passing the given distance."},
            {"new_element.usage.map_sound3d.put", "Place a ground-fixed 3D sound source at the given distance; it plays continuously."},
            {"new_element.usage.rolling_noise.change", "Set rolling noise from the given distance onward."},
            {"new_element.usage.flange_noise.change", "Set flange noise from the given distance onward."},
            {"new_element.usage.joint_noise.play", "Play joint noise when passing the given distance, according to train speed."},
            {"new_element.usage.background.change", "Change the background at the given distance."},
            {"new_element.usage.adhesion.change", "Set wheel-rail adhesion characteristics from the given distance onward."},
            {"new_element.usage.cab_illuminance.set", "Legacy alias for CabIlluminance.Interpolate: set cab illuminance at the given distance; values between points are linearly interpolated."},
            {"new_element.usage.cab_illuminance.interpolate", "Set cab illuminance at the given distance; values between points are linearly interpolated."},
            {"new_element.usage.fog.set", "Legacy alias for Fog.Interpolate: set the fog effect at the given distance; values between points are linearly interpolated."},
            {"new_element.usage.fog.interpolate", "Set the fog effect at the given distance; values between points are linearly interpolated."},
            {"new_element.usage.light.ambient", "Set the ambient-light color at distance 0. Each RGB component must be from 0 to 1; only one Light.Ambient declaration is allowed in the logical map."},
            {"new_element.usage.light.diffuse", "Set the parallel-light color at distance 0. Each RGB component must be from 0 to 1; only one Light.Diffuse declaration is allowed in the logical map."},
            {"new_element.usage.light.direction", "Set the parallel-light direction at distance 0. Only one Light.Direction declaration is allowed in the logical map."},
            {"new_element.usage.draw_distance.change", "Set the scenery draw distance from the given distance onward."},
            {"status.edit.no_distance_source", "No editable map source file is available."},
            {"status.new_file.no_reference_target", "No editable source file is available for reference."},
            {"context.station_list.insert_above", "Insert Row Above"}, {"context.station_list.insert_below", "Insert Row Below"}, {"context.station_list.move_up", "Move Entire Row Up"}, {"context.station_list.move_down", "Move Entire Row Down"}, {"context.station_list.clear_cell", "Clear Cell"}, {"context.station_list.delete_row", "Delete Entire Row"}, {"context.other_track.rename", "Rename"},
            {"context.editable_list.insert_above", "Insert Row Above"}, {"context.editable_list.insert_below", "Insert Row Below"}, {"context.editable_list.move_up", "Move Entire Row Up"}, {"context.editable_list.move_down", "Move Entire Row Down"}, {"context.editable_list.clear_cell", "Clear Cell"}, {"context.editable_list.delete_row", "Delete Entire Row"}, {"context.signal_aspect.add_glare", "Add Glare"}, {"context.signal_aspect.delete_glare", "Delete Glare"}, {"context.plan_marker.structure", "Structure"}, {"context.plan_marker.repeater", "Repeater"}, {"context.plan_marker.signal", "Map Signal"}, {"context.plan_marker.other_train_stop", "Other Train Stop"}, {"context.plan_marker.other_track_change", "Other Track Change"},
            {"dialog.select_resource_file", "Select Resource File"}, {"dialog.select_include_file", "Select Included Map File"}, {"dialog.select_resource_list_file", "Select Resource List File"}, {"dialog.filter.audio_files", "Audio files"}, {"dialog.filter.model_files", "Model files"}, {"dialog.filter.all_files", "All files"}, {"dialog.filter.map_files", "BVE map/scenario files"}, {"dialog.filter.resource_list_files", "Resource list files"}, {"dialog.scenario_route_select_title", "Multiple Map Candidates in Scenario"}, {"status.edit.relative_path_fallback", "Unable to create a relative path; using an absolute path."}, {"status.edit.not_structure_list_file", "This file is not a Structure List file."}, {"status.edit.not_signal_aspect_list_file", "This file is not a Signal Aspects List file."}, {"status.edit.not_sound_list_file", "This file is not a Sound List file."},
            {"status.edit.not_station_list_file", "This file is not a Station List file."},
            {"status.edit.apply_list_before_save", "Apply all table drafts before saving."}, {"dialog.apply_list_before_save", "Apply every list table's changes before saving."},
            {"button.save_changes_and_exit", "Save Changes and Exit"}, {"button.discard_changes_and_exit", "Discard Changes and Exit"}, {"button.save_changes_and_close_edit", "Save Changes and Close Editing"}, {"button.discard_changes_and_close_edit", "Discard Changes and Close Editing"},
            {"button.model_list", "Model List"}, {"button.start_scene_preview", "Start 3D Scene Preview"}, {"button.background_color", "Background Color"}, {"button.find", "Find"}, {"button.find_unused_structure_models", "Search unused structure models"}, {"button.find_unused_signal_aspects", "Search unused signal aspects"}, {"button.find_unused_sound_files", "Search unused sounds"}, {"button.find_unused_sound_3d_files", "Search unused 3D sounds"},
            {"button.import_bg", "Import"}, {"button.adjust_bg", "Adjust"}, {"button.align_to_station", "Align to Station"}, {"button.jump", "Jump"},
            {"frame.controls", "Controls"}, {"frame.console", "Console"}, {"frame.file_structure_diagram", "File Structure Diagram"}, {"frame.text_preview", "Text Preview"}, {"frame.plots", "2D View"}, {"frame.othertracks", "Other Tracks"}, {"frame.station_list", "Station List"}, {"frame.station_positions", "Station Positions"}, {"frame.station_definitions", "Station Definitions"},
            {"frame.structures", "Map Structure List"}, {"frame.structures_put_between", "Map Structure List (PutBetween)"}, {"frame.structure_models", "Structure Model List"}, {"frame.sound_list", "Sound File List"}, {"frame.sound_3d_list", "3D Sound File List"}, {"frame.repeaters", "Repeater List"}, {"frame.signal_aspects", "Signal Aspect List"}, {"frame.signals", "Map Signal List"}, {"frame.beacons", "Beacon List"}, {"frame.irregularities", "Track Irregularity List"}, {"frame.adhesions", "Adhesion Change Point List"}, {"frame.speed_limits", "Speed Limit Point List"}, {"frame.cab_illuminance", "Cab Illuminance Change Point List"}, {"frame.fogs", "Fog Change Point List"}, {"frame.legacy_fogs", "Legacy Fog Change Point List"}, {"frame.lighting", "Lighting Effects"}, {"frame.draw_distances", "Draw Distance Change Point List"}, {"frame.aux_info", "Auxiliary Info"}, {"frame.model_preview", "3D-Model Preview"}, {"frame.scene_preview", "3D-Scene Preview"},
            {"label.light_statement_missing", "This map does not contain this statement."},
            {"frame.chart_visibility", "Chart Visibility"}, {"frame.grid", "Grid"}, {"frame.mode", "Mode"}, {"frame.bgimage", "Background Image"},
            {"aux.station", "Station"}, {"aux.scenery", "Structures"}, {"aux.track_geometry", "Track Geometry"}, {"aux.signal", "Signal"}, {"aux.sound", "Sound"}, {"aux.effects", "Effects"}, {"aux.scene_3d", "3D Scene"}, {"aux.other", "Other"},
            {"column.file_name", "File Name"}, {"column.show", "Show"}, {"column.key", "Key"}, {"column.from", "From"}, {"column.to", "To"}, {"column.color", "Color"},
            {"find.partial_match", "Partial Match"}, {"find.exact_match", "Exact Match"},
            {"chk.station_pos", "Station Position"}, {"chk.station_name", "Station Name"}, {"chk.station_mileage", "Station Mileage"},
            {"chk.gradient_pos", "Gradient Change Points"}, {"chk.gradient_val", "Gradient Values"}, {"chk.curve_val", "Curve Radius"},
            {"chk.prof_othert", "Other Tracks (Profile)"}, {"chk.speedlimit", "Speed Limit"}, {"chk.irregularity_markers", "Track Irregularity Change Points"}, {"chk.beacon_markers", "Beacon Positions"}, {"chk.pretrain_markers", "PreTrain Pass Points"}, {"chk.other_train_paths", "Other Train Paths"}, {"chk.adhesion_markers", "Adhesion Change Points"}, {"chk.cab_illuminance_markers", "Cab Illuminance Change Points"}, {"chk.fog_markers", "Fog Change Points"}, {"chk.draw_distance_markers", "Draw Distance Change Points"}, {"chk.scene_owntrack_markers", "Own Track Markers"}, {"chk.scene_current_position_on_plan", "Show Current Position on Plan"}, {"chk.console_window", "Console Window"},
            {"chk.view_2d_window", "2D View Window"}, {"chk.select_all", "Select All"}, {"chk.edit_mode", "Enable Edit"},
            {"chk.edit_mode_warning_dont_show", "Don't show again"},
            {"chk.gradient_graph", "Profile"}, {"chk.curve_graph", "Radius"}, {"chk.bgimg_show", "Show"},
            {"grid.fixed", "Fixed"}, {"grid.movable", "Movable"}, {"grid.none", "None"},
            {"mode.pan", "Move"}, {"mode.select", "Select"}, {"mode.mileage_select", "Mileage Select"}, {"mode.measure", "Measure"}, {"label.minimum", "Min"}, {"label.maximum", "Max"}, {"label.interval", "Interval"}, {"label.station_jump", "Station Jump"}, {"label.distance_jump", "Jump to distance(m)"}, {"label.source_file", "Source"}, {"label.source_position", "Position"}, {"label.source_distance_string", "Source Distance String"}, {"label.raw_statement", "Raw statement"}, {"label.source_section", "Source section"}, {"label.include_context", "Include context"}, {"label.pending_insertion", "Statement to insert"},
            {"canvas.plan", "Plan"}, {"canvas.profile", "Gradient / Height"}, {"canvas.radius", "Curve Radius"},
            {"plot.profile", "Profile"}, {"plot.radius", "Curve Radius"}, {"plot.level", "Level"}, {"unit.m", "m"},
            {"info.mileage", "Mileage"}, {"info.elevation", "Elevation"}, {"info.gradient", "Gradient"}, {"info.radius", "Curve Radius"},
            {"info.speedlimit", "Speed Limit"}, {"info.no_limit", "None"},
            {"hint.pick_bg_station", "Double-click the station position on the background image"}, {"hint.distance_choose_boundary", "Choose one of the parser-confirmed statement boundaries highlighted below."},
            {"label.bgimg_x", "X (m)"}, {"label.bgimg_y", "Y (m)"}, {"label.bgimg_width", "Width (m)"},
            {"label.bgimg_height", "Height (m)"}, {"label.bgimg_rotation", "Rotation (deg)"}, {"label.bgimg_brightness", "Brightness (%)"},
            {"label.font_size", "Text size"}, {"label.ui_component_size", "UI component size"}, {"label.station_marker_size", "Marker size"}, {"label.own_track_line_width", "Own track line width"}, {"label.other_track_line_width", "Other track line width"}, {"label.chart_marker_line_width", "Chart marker line width"}, {"label.background_grid_line_width", "Background grid line width"}, {"label.scene_auto_load_on_map_open", "Automatically load scene preview when opening a map"}, {"label.scene_fog_effect", "Fog effect"}, {"label.scene_map_draw_distance", "Adjust draw distance from map statements"}, {"label.scene_draw_distance", "Draw distance"}, {"label.scene_edit_component_size", "Edit component size"}, {"label.scene_camera_speed", "Camera movement speed"}, {"label.scene_performance_warning", "Performance warning"}, {"label.scene_instance_warning_threshold", "Warning threshold"}, {"label.scene_instance_critical_warning_threshold", "Critical warning threshold"}, {"label.ui_theme_color", "Interface theme color"},
            {"label.font_size_current", "Text size:"}, {"label.ui_component_size_current", "Component size:"}, {"label.ui_theme_color_current", "Theme color:"}, {"label.font_size_preview", "Preview text"},
            {"label.quick_colors", "Quick colors"}, {"color.white", "White"}, {"color.black", "Black"}, {"color.gray", "Gray"}, {"color.blue", "Blue"}, {"color.green", "Green"},
            {"status.edit.repeater_end_before_begin", "Repeater End distance cannot be less than Begin distance"}, {"status.edit.transition_start_after_distance", "Transition start distance cannot be greater than its statement distance"},
            {"status.no_map", "No map loaded"}, {"status.resource_list_no_map", "No map is currently loaded"}, {"status.resource_list_not_specified", "The current map does not specify {resource_list}."}, {"status.loading", "Loading..."}, {"status.scene_loading", "Loading..."}, {"status.ready", "Ready"}, {"status.text_preview_load_failed", "Unable to load text preview."}, {"status.distance_no_boundaries", "No selectable statement boundary was returned."}, {"status.edit.pending", "Pending change"}, {"status.edit.pending_delete", "Pending delete"}, {"status.edit.reverted", "Reverted"}, {"status.edit.no_changes", "No changes"}, {"status.edit.required_field", "Required field is empty"}, {"status.edit.invalid_number", "Invalid number"}, {"status.edit.repeater_key_conflict", "Repeater key overlaps another interval"}, {"status.edit.other_track_key_conflict", "Other-track key already exists"}, {"status.edit.applying", "Applying changes..."}, {"status.edit.reverting", "Reverting edits..."}, {"status.edit.saving", "Saving..."}, {"status.edit.applied_to_preview", "Applied to preview"}, {"status.edit.saved", "Saved"}, {"status.edit.mode_enabled", "Edit mode enabled"}, {"status.edit.mode_disabled", "Edit mode disabled"}, {"status.edit.loading_metadata", "Loading edit metadata..."}, {"status.edit.disable_blocked_unsaved", "Save or revert pending edits before disabling edit mode."}, {"status.edit.distance_resolution_required", "A source placement choice is required"}, {"status.edit.distance_resolution_cancelled", "Source placement selection cancelled"},
            {"status.edit.apply_station_list_before_save", "Apply Station Definitions before saving."},
            {"status.find.no_match", "No matching text found"}, {"status.find.match", "Found ({current}/{total})"}, {"status.unused_structure_models.match", "Found unused models ({unused}/{total})"}, {"status.unused_structure_models.no_match", "No unused models found"}, {"status.unused_signal_aspects.match", "Found unused signal aspects ({unused}/{total})"}, {"status.unused_signal_aspects.no_match", "No unused signal aspects found"}, {"status.unused_sound_files.match", "Found unused sounds ({unused}/{total})"}, {"status.unused_sound_files.no_match", "No unused sounds found"}, {"status.unused_sound_3d_files.match", "Found unused 3D sounds ({unused}/{total})"}, {"status.unused_sound_3d_files.no_match", "No unused 3D sounds found"},
            {"dialog.edit_mode_warning_title", "Enable Edit Mode"}, {"dialog.resource_list_file_change_title", "Change Resource List File"},
            {"dialog.resource_list_file_change_message", "Changing the file discards this list's unsaved edits to the old file contents. Continue?"},
            {"dialog.edit_mode_warning_message", "Do you want to enable edit mode?\nEditing is an unstable, experimental feature and may make destructive changes to map files. Back up your map files first, or manage them with version control such as Git."},
            {"dialog.other_track_rename_title", "Rename Other Track"}, {"label.track_key", "trackKey"},
            {"dialog.repeater_change_point_insert_title", "Insert Repeater Change Point"},
            {"dialog.repeater_change_point_insert_message", "A continuous placement with the same name already exists in the current interval. The statement will be inserted as a change point. Continue?"},
            {"dialog.repeater_extra_end_title", "Repeater End Already Exists"},
            {"dialog.repeater_extra_end_message", "The continuous placement with the same name already has an End statement. To adjust it, edit the end position directly in Properties/Edit."},
            {"dialog.ui_settings", "UI Settings"}, {"dialog.canvas_element_sizes", "Canvas Element Sizes"}, {"dialog.canvas_3d_settings", "3D Canvas Settings"}, {"dialog.element_properties", "Properties/Edit"}, {"dialog.distance_resolution_title", "Distance Placement"}, {"dialog.distance_resolution_message", "Unable to determine where to move the statement automatically. Select manually?"}, {"dialog.distance_expression_title", "Distance Expression"}, {"dialog.distance_variable_message", "Variable [{variable}] has multiple values in this context. Edit the source expression manually?"}, {"dialog.reload_unsaved_title", "Reload from Disk"}, {"dialog.reload_unsaved_message", "There are unsaved changes. Reload from disk?"}, {"dialog.revert_all_edits_title", "Revert All Changes"}, {"dialog.revert_all_edits_message", "Revert all unsaved changes? This restores the in-memory map to its last saved state. This action cannot be redone."}, {"dialog.unsaved_changes_title", "Unsaved Changes"}, {"dialog.unsaved_exit_message", "There are unsaved changes. Are you sure you want to exit?"}, {"dialog.unsaved_close_edit_message", "There are unsaved changes. Are you sure you want to close editing?"}, {"dialog.bgimage_adjust", "Adjust Background Image"}, {"dialog.align_to_station", "Align Background to Stations"}, {"button.pick_on_bg", "Pick station on Plan"}, {"button.pick_on_bg_ok", "Picked"},
            {"dialog.apply_station_list_before_save", "Apply the Station Definitions table changes before saving."},
            {"dialog.open_document_unsaved_title", "Open File"}, {"dialog.open_document_unsaved_message", "There are unsaved changes. Open another file and discard them?"},
            {"about.text", "komapedit\nVersion 0.7.9\nCopyright © 2026 Sapporo_ningyo\nBased on kobushi-trackviewer\nCopyright © 2021-2024 konawasabi\nLicense: Apache License 2.0\nThird-party: Dear ImGui (MIT), ImPlot (MIT)\nSee LICENSE, NOTICE, and THIRD_PARTY_NOTICES.md"}
        };
        zh = {
            {"menu.import_submap", "导入子地图..."},
            {"menu.new_submap", "新建子地图..."},
            {"dialog.create_include_file", "创建子地图文件"},
            {"status.edit.include_create_failed", "无法创建子地图文件。"},
            {"frame.sections", "闭塞列表"},
            {"frame.section_begins", "闭塞开始位置"},
            {"frame.section_speed_limits", "闭塞限速"},
            {"frame.variables", "变量列表"},
            {"frame.scenario_file", "场景文件"},
            {"menu.map_info.sections", "闭塞"},
            {"menu.map_info.variables", "变量"},
            {"menu.map_info.scenario_file", "场景文件"},
            {"menu.locate_in_section_list", "在闭塞列表中定位"},
            {"chk.section_markers", "闭塞标记"},
            {"label.source_path", "源文件路径"},
            {"label.enable_time", "启用时间"},
            {"column.variable", "变量"},
            {"column.value", "赋值"},
            {"scene.route_info.speed_limit", "限速:"},
            {"scene.route_info.signal", "信号:"},
            {"dialog.coordinate_offset_discard_title", "去除坐标偏移"},
            {"dialog.coordinate_offset_discard_message", "此布景的所有坐标偏移将被丢弃，是否继续？"},
            {"label.repeater_end_source", "结束位置源："}, {"value.none", "无"}, {"value.own_track", "(主轨道)"},
            {"value.tilt.always_level", "始终水平"}, {"value.tilt.follow_gradient", "随坡度联动"}, {"value.tilt.follow_cant", "随超高联动"}, {"value.tilt.follow_gradient_and_cant", "随坡度和超高联动"},
            {"value.door.open_left", "左侧开门"}, {"value.door.do_not_open", "不开门"}, {"value.door.open_right", "右侧开门"},
            {"status.transition_unpaired", "此 BeginTransition 没有对应的 Begin/End，无法编辑或删除。"},
            {"label.repeater_structure_keys", "结构键列表"},
            {"label.section_parameters", "参数"},
            {"status.repeater_multiple_begins", "此Repeater存在多个Begin语句"},
            {"button.add_repeater_end_position", "添加结束位置"},
            {"button.insert_repeater_change_point", "插入变化点"},
            {"status.map_loading", "正在加载地图..."}, {"status.map_loaded", "地图加载完成"}, {"status.map_load_failed", "地图加载失败"},
            {"status.scene_preview_loading", "正在加载3D场景预览..."}, {"status.scene_preview_loaded", "3D场景预览已加载"}, {"status.scene_preview_failed", "3D场景预览加载失败"}, {"status.scene_preview_stopped", "3D场景预览已停止"},
            {"status.no_errors_warnings", "没有错误或警告"}, {"frame.errors_warnings", "错误与警告"},
            {"scene.route_info.straight", "直线"}, {"scene.route_info.interpolate_unsupported", "插值（不支持）"}, {"scene.route_info.next_station", "下一站："}, {"scene.route_info.no_station_ahead", "前方无车站"},
            {"dialog.distance_expression_message", "是否手动编辑距离源字符串？"},
            {"dialog.signal_full_form_convert_title", "转换 Signal.Put"}, {"dialog.signal_full_form_convert_message", "当前信号机使用 Signal.Put 短式。是否先转换为完整式，再编辑 Z、旋转、倾斜或跨度参数？"},
            {"dialog.structure_z_rebase_title", "重新设置里程"}, {"dialog.structure_z_rebase_message", "当前模型的z轴偏移大于5m，是否重新设置里程？"},
            {"app.title", "komapedit"},
            {"menu.map_info.other_trains", "他列车"},
            {"frame.other_trains", "他列车列表"},
            {"frame.other_train_definitions", "定义"},
            {"frame.other_train_stops", "停止位置"},
            {"frame.structure_put", "Put"},
            {"frame.structure_put_between", "PutBetween"},
            {"menu.locate_in_other_train_stop_list", "定位至他列车停止位置列表"},
            {"frame.map_sounds", "地图音效列表"},
            {"frame.map_sound_3d", "固定音源音效"},
            {"button.map_sound_list", "地图音效列表"},
            {"button.map_sound_3d_list", "地图3D音效列表"},
            {"chk.map_sound_markers", "音效播放位置"},
            {"chk.map_sound_3d_markers", "固定音效位置"},
            {"menu.locate_in_map_sound_list", "定位至地图音效列表"},
            {"menu.locate_in_map_sound_3d_list", "定位至地图3D音效列表"},
            {"frame.rolling_noises", "走行音变化点列表"},
            {"chk.rolling_noise_markers", "走行音变化点"},
            {"menu.locate_in_rolling_noise_list", "定位至走行音变化点列表"},
            {"frame.flange_noises", "轮缘摩擦音效变化点列表"},
            {"chk.flange_noise_markers", "轮缘摩擦音效变化点"},
            {"menu.locate_in_flange_noise_list", "定位至轮缘摩擦音效变化点列表"},
            {"frame.joint_noises", "道岔音效播放点列表"},
            {"chk.joint_noise_markers", "道岔音效播放点"},
            {"menu.locate_in_joint_noise_list", "定位至道岔音效播放点列表"},
            {"frame.backgrounds", "背景变化点列表"},
            {"chk.background_markers", "背景变化点"},
            {"menu.locate_in_background_list", "定位至背景变化点列表"},
            {"menu.file", "文件"}, {"menu.options", "选项"}, {"menu.map_info", "地图信息列表"}, {"menu.view_2d", "2D视图"}, {"menu.lang", "语言"}, {"menu.help", "帮助"},
            {"menu.map_info.othertracks", "其他轨道"}, {"menu.map_info.station", "车站列表"}, {"menu.map_info.signal_aspects", "信号现示"}, {"menu.map_info.signals", "地图信号"}, {"menu.map_info.beacons", "应答器"},
            {"menu.map_info.structures", "地图布景"}, {"menu.map_info.structures_put_between", "地图布景(Putbetween)"}, {"menu.map_info.structure_models", "布景模型"}, {"menu.map_info.sound_files", "音效文件"}, {"menu.map_info.sound_3d_files", "3D音效文件"}, {"menu.map_info.map_sounds", "地图音效"},
            {"menu.map_info.map_sound_3d", "地图3D音效"}, {"menu.map_info.repeaters", "连续布景"}, {"menu.map_info.irregularities", "轨道变位"}, {"menu.map_info.rolling_noises", "走行音变化点"}, {"menu.map_info.flange_noises", "轮缘摩擦音效变化点"},
            {"menu.map_info.joint_noises", "道岔音效播放点"}, {"menu.map_info.backgrounds", "背景变化点"}, {"menu.map_info.adhesions", "粘着特性变化点"}, {"menu.map_info.speed_limits", "限速点"}, {"menu.map_info.cab_illuminance", "驾驶台亮度变化点"}, {"menu.map_info.fogs", "雾效果变化点"}, {"menu.map_info.legacy_fogs", "旧式雾效果变化点"}, {"menu.map_info.lighting", "光照"}, {"menu.map_info.draw_distances", "绘制距离变化点"},
            {"menu.open", "打开..."}, {"menu.recent_maps", "最近打开的地图"}, {"menu.none", "无"}, {"menu.clear_recent_maps", "清除列表"}, {"menu.reload", "重新加载"}, {"menu.export_csv", "导出 CSV..."}, {"menu.exit", "退出"},
            {"menu.controlpoints", "控制点间隔..."}, {"menu.plotlimit", "绘图范围..."}, {"menu.ui_settings", "用户界面设置..."}, {"menu.canvas_2d_settings", "2D画布设置"}, {"menu.canvas_element_sizes", "画布元素尺寸"}, {"menu.canvas_3d_settings", "3D画布设置"}, {"menu.about", "关于"},
            {"menu.online_docs", "在线文档"}, {"menu.report_bugs", "报告问题"}, {"menu.open_in_explorer", "在文件资源管理器中打开"}, {"menu.select_file", "选择文件"}, {"menu.preview_text", "预览文本"}, {"menu.unreference_include", "解除引用"}, {"menu.change_include_file", "更换文件..."}, {"menu.change_file", "更换文件..."}, {"menu.locate_on_plan", "定位至平面图"}, {"menu.locate_in_scene_preview", "定位至3D场景预览"}, {"menu.locate_in_structure_list", "定位至地图布景列表"}, {"menu.locate_in_structure_put_between_list", "定位至地图布景列表(Putbetween)"}, {"menu.locate_in_repeater_list", "定位至连续布景列表"}, {"menu.repeater_delete_all", "全部删除"}, {"menu.repeater_delete_change_point", "删除对应变化点"}, {"menu.repeater_trim_to_change_point", "修剪至变化点"}, {"menu.repeater_start_from_change_point", "从变化点开始"}, {"menu.jump_to_repeater_start_position", "跳至起始位置"}, {"menu.jump_to_repeater_end_or_change_position", "跳至结束/变化位置"}, {"menu.locate_in_signal_list", "定位至地图信号列表"}, {"menu.locate_in_beacon_list", "定位至应答器列表"}, {"menu.locate_in_irregularity_list", "定位至轨道变位列表"}, {"menu.locate_in_adhesion_list", "定位至粘着特性变化点列表"}, {"menu.locate_in_cab_illuminance_list", "定位至驾驶台亮度变化点列表"}, {"menu.locate_in_fog_list", "定位至雾效果变化点列表"}, {"menu.locate_in_legacy_fog_list", "定位至旧式雾效果变化点列表"}, {"menu.locate_in_draw_distance_list", "定位至绘制距离变化点列表"}, {"menu.locate_in_speed_limit_list", "在限速点列表中定位"},
            {"menu.view_3d", "3D视图"}, {"menu.structure_model_preview", "布景模型预览"}, {"menu.scene_preview", "3D场景预览"}, {"menu.preview_model", "预览模型"}, {"menu.switch_signal_aspect", "切换信号现示"}, {"menu.find_in_structure_models", "在布景模型列表中查找"}, {"menu.find_in_signal_aspects", "在信号现示列表中查找"}, {"menu.find_in_sound_files", "在音效文件列表中查找"}, {"menu.find_in_sound_3d_files", "在3D音效文件列表中查找"},
            {"menu.use_this_model", "使用此模型"}, {"menu.use_this_sound", "使用此音效"},
            {"button.open", "打开"}, {"button.reload", "重新加载"}, {"button.reload_geometry", "重新加载线形"}, {"button.reload_scene_models", "重新加载（模型）"}, {"button.export_csv", "导出 CSV"},
            {"button.structure_list", "地图布景列表"}, {"button.repeater_list", "连续布景列表"},
            {"button.apply", "应用"}, {"button.apply_jump_to_edit", "应用并编辑"}, {"button.new", "新建"}, {"button.reset", "重置"}, {"button.revert", "撤销"}, {"button.save", "保存"}, {"button.delete", "删除"}, {"button.ok", "确定"}, {"button.cancel", "取消"}, {"button.clear", "清除"}, {"button.copy", "复制"}, {"button.close", "关闭"}, {"button.previous", "上一个"}, {"button.next", "下一个"}, {"button.confirm_reuse", "仍然复用"}, {"button.manual_select", "手动选择"},
            {"button.confirm_and_load", "确定并载入"},
            {"button.add_coordinate_offsets", "添加坐标偏移"}, {"button.remove_coordinate_offsets", "去除坐标偏移"},
            {"button.add_map_element", "添加地图元素"}, {"menu.add_map_element_at_current_mileage", "在当前里程新建地图元素"}, {"dialog.new_element_wizard", "新建地图元素向导"}, {"label.new_element_target_file", "目标源文件"}, {"label.transition_start", "缓和曲线起点里程"},
            {"menu.new_file", "新建..."}, {"dialog.new_file_wizard", "新建文件向导"}, {"new_file.category.presets", "预设"}, {"new_file.category.map", "地图"}, {"new_file.category.resource_lists", "地图资源列表"},
            {"new_file.usage.map", "新建空白的 BveTs Map 2.02 地图源文件。"}, {"new_file.usage.structure", "新建用于地图布景的空白 Structure List 文件。"}, {"new_file.usage.signal", "新建用于信号定义的空白 Signal Aspects List 文件。"}, {"new_file.usage.sound", "新建用于列车和环境声音的空白 Sound List 文件。"}, {"new_file.usage.sound3d", "新建用于三维声音的空白 Sound List 文件。"}, {"new_file.usage.station", "新建用于车站定义的空白 Station List 文件。"},
            {"label.new_file_name", "文件名"}, {"label.new_file_directory", "文件路径"}, {"label.new_file_reference", "在以下文件中引用"}, {"button.select_directory", "选择目录"}, {"button.confirm", "确定"}, {"dialog.select_export_folder", "选择导出目录"}, {"dialog.select_new_file_directory", "选择文件目录"},
            {"status.new_file.invalid_path", "请输入有效的文件名和现有目录。"}, {"status.new_file.create_failed", "无法新建文件。"}, {"status.new_file.created", "已新建文件。"}, {"status.new_file.reference_requires_edit", "引用文件需要处于编辑模式。"}, {"status.new_file.resource_list_already_loaded", "该资源列表类型已经加载。"}, {"status.new_file.reference_failed", "文件已新建，但未能暂存其引用。"},
            {"button.import_file", "导入文件"}, {"button.new_or_import_file", "新建或导入文件"}, {"button.add_row", "新增行"},
            {"resource_list.name.station", "车站列表"}, {"resource_list.name.structure", "布景模型列表"}, {"resource_list.name.signal", "信号现示列表"}, {"resource_list.name.sound", "音效列表"}, {"resource_list.name.sound3d", "固定音源音效列表"},
            {"status.new_file.reused", "已复用已有文件。"}, {"status.new_file.resource_list_already_present", "当前地图中已存在{resource_list}，如需替换，请右键点击对应列表最上方的“文件路径”。"},
            {"new_element.usage.structure.put", "在指定位置放置一个地图布景实例。"},
            {"new_element.usage.structure.put0", "放置无坐标偏移的布景；仅设置倾斜方式和弦长。"},
            {"new_element.usage.repeater.begin", "新建 Repeater.Begin、Repeater.End 或两者；Begin 使用坐标偏移。"},
            {"new_element.usage.repeater.begin0", "新建 Repeater.Begin0、Repeater.End 或两者；Begin0 不使用坐标偏移。"},
            {"chk.new_element_repeater_add_begin", "添加Begin"}, {"chk.new_element_repeater_add_end", "添加End"}, {"chk.new_element_include_parameter", "包含此参数"},
            {"new_element.usage.curve", "新建受支持的曲线起始位置、结束位置或两者。"},
            {"new_element.usage.gradient", "新建受支持的坡道起始位置、结束位置或两者。"},
            {"chk.new_element_add_start", "添加起始位置"}, {"chk.new_element_add_end", "添加结束位置"},
            {"chk.new_element_own_track_add_transition", "添加缓和曲线起点"}, {"chk.new_element_add_parameter", "添加此参数"},
            {"new_element.usage.structure.put_between", "在两条轨道之间放置布景，并根据两轨道间距使其变形。"},
            {"new_element.usage.station.put", "在指定里程设置列车停车位置。"},
            {"new_element.usage.signal.put", "在指定位置和闭塞区间放置信号机。"},
            {"new_element.usage.speedlimit.begin", "在指定里程和速度开始限速。"},
            {"new_element.usage.speedlimit.end", "在指定里程结束限速。"},
            {"new_element.usage.section.begin", "使用列出的信号索引开始新的闭塞。"},
            {"new_element.usage.section.beginnew", "Section.Begin 的旧式别名：使用列出的信号索引开始新的闭塞。"},
            {"new_element.usage.section.setspeedlimit", "在指定里程设置信号现示的允许速度。"},
            {"new_element.usage.section.signal_speedlimit", "Section.SetSpeedLimit 的旧式别名：在指定里程设置信号现示的允许速度。"},
            {"new_element.usage.irregularity.change", "从指定里程起设置轨道变位。"},
            {"new_element.usage.other_track.position", "在当前里程设置他轨道位置（等同同时设置 X/Y 插值）。"},
            {"new_element.usage.other_track.x_interpolate", "在当前里程设置他轨道 X 位置，并与上一 X 点之间插值。"},
            {"new_element.usage.other_track.y_interpolate", "在当前里程设置他轨道 Y 位置，并与上一 Y 点之间插值。"},
            {"new_element.usage.other_track.cant_set_gauge", "设置当前里程之后的他轨道轨距（用于将超高换算为角度）。"},
            {"new_element.usage.other_track.cant_set_center", "设置当前里程之后他轨道超高的旋转中心。"},
            {"new_element.usage.other_track.cant_set_function", "设置当前里程之后他轨道超高缓和曲线的函数。"},
            {"new_element.usage.other_track.cant_begin_transition", "从当前里程开始他轨道的超高缓和。"},
            {"new_element.usage.other_track.cant_begin", "在当前里程结束超高缓和，并开始恒定超高。"},
            {"new_element.usage.other_track.cant_end", "在当前里程结束他轨道超高。"},
            {"new_element.usage.other_track.cant_interpolate", "设置当前里程的他轨道超高，并按已设函数与上一点插值。"},
            {"new_element.usage.beacon.put", "在指定里程定义应答器发送事件。"},
            {"new_element.usage.map_sound.play", "通过指定里程时播放一次音效。"},
            {"new_element.usage.map_sound3d.put", "在指定里程放置固定于地面的 3D 音源；音效会连续播放。"},
            {"new_element.usage.rolling_noise.change", "从指定里程起设置走行音。"},
            {"new_element.usage.flange_noise.change", "从指定里程起设置轮缘摩擦音效。"},
            {"new_element.usage.joint_noise.play", "通过指定里程时按列车速度播放道岔音效。"},
            {"new_element.usage.background.change", "在指定里程更换背景。"},
            {"new_element.usage.adhesion.change", "从指定里程起设置轮轨粘着特性。"},
            {"new_element.usage.cab_illuminance.set", "CabIlluminance.Interpolate 的旧式别名：在指定里程设置驾驶台亮度；各点之间线性插值。"},
            {"new_element.usage.cab_illuminance.interpolate", "在指定里程设置驾驶台亮度；各点之间线性插值。"},
            {"new_element.usage.fog.set", "Fog.Interpolate 的旧式别名：在指定里程设置雾效果；各点之间线性插值。"},
            {"new_element.usage.fog.interpolate", "在指定里程设置雾效果；各点之间线性插值。"},
            {"new_element.usage.light.ambient", "在里程 0 设置环境光颜色。RGB 各分量必须在 0 至 1 之间；逻辑地图中只能有一条 Light.Ambient 声明。"},
            {"new_element.usage.light.diffuse", "在里程 0 设置平行光颜色。RGB 各分量必须在 0 至 1 之间；逻辑地图中只能有一条 Light.Diffuse 声明。"},
            {"new_element.usage.light.direction", "在里程 0 设置平行光方向。逻辑地图中只能有一条 Light.Direction 声明。"},
            {"new_element.usage.draw_distance.change", "从指定里程起设置风景绘制距离。"},
            {"status.edit.no_distance_source", "没有可编辑的地图源文件。"},
            {"status.new_file.no_reference_target", "无可引用的编辑源文件。"},
            {"context.station_list.insert_above", "在上方新增行"}, {"context.station_list.insert_below", "在下方新增行"}, {"context.station_list.move_up", "上移整行"}, {"context.station_list.move_down", "下移整行"}, {"context.station_list.clear_cell", "清除单元格"}, {"context.station_list.delete_row", "删除整行"}, {"context.other_track.rename", "重命名"},
            {"context.editable_list.insert_above", "在上方新增行"}, {"context.editable_list.insert_below", "在下方新增行"}, {"context.editable_list.move_up", "上移整行"}, {"context.editable_list.move_down", "下移整行"}, {"context.editable_list.clear_cell", "清除单元格"}, {"context.editable_list.delete_row", "删除整行"}, {"context.signal_aspect.add_glare", "新增眩光"}, {"context.signal_aspect.delete_glare", "删除眩光"}, {"context.plan_marker.structure", "布景"}, {"context.plan_marker.repeater", "连续布景"}, {"context.plan_marker.signal", "地图信号"}, {"context.plan_marker.other_train_stop", "他列车停止位置"}, {"context.plan_marker.other_track_change", "其他轨道变化点"},
            {"dialog.select_resource_file", "选择资源文件"}, {"dialog.select_include_file", "选择子地图文件"}, {"dialog.select_resource_list_file", "选择资源列表文件"}, {"dialog.filter.audio_files", "音效文件"}, {"dialog.filter.model_files", "模型文件"}, {"dialog.filter.all_files", "所有文件"}, {"dialog.filter.map_files", "BVE 地图/场景文件"}, {"dialog.filter.resource_list_files", "资源列表文件"}, {"dialog.scenario_route_select_title", "当前场景存在多个地图候选，请选择1个加载"}, {"status.edit.relative_path_fallback", "无法生成相对路径，已使用绝对路径。"}, {"status.edit.not_structure_list_file", "此文件不是布景模型列表文件。"}, {"status.edit.not_signal_aspect_list_file", "此文件不是信号现示列表文件。"}, {"status.edit.not_sound_list_file", "此文件不是音效列表文件。"},
            {"status.edit.not_station_list_file", "此文件不是车站列表文件。"},
            {"status.edit.apply_list_before_save", "保存前请先应用所有列表表格中的更改。"}, {"dialog.apply_list_before_save", "保存前请先应用所有列表表格中的更改。"},
            {"button.save_changes_and_exit", "保存更改并退出"}, {"button.discard_changes_and_exit", "放弃更改并退出"}, {"button.save_changes_and_close_edit", "保存更改并关闭编辑"}, {"button.discard_changes_and_close_edit", "放弃更改并关闭编辑"},
            {"button.model_list", "模型列表"}, {"button.start_scene_preview", "启动3D场景预览"}, {"button.background_color", "背景颜色"}, {"button.find", "查找"}, {"button.find_unused_structure_models", "查找未使用布景模型"}, {"button.find_unused_signal_aspects", "查找未使用信号现示"}, {"button.find_unused_sound_files", "查找未使用音效"}, {"button.find_unused_sound_3d_files", "查找未使用3D音效"},
            {"button.import_bg", "导入"}, {"button.adjust_bg", "调整"}, {"button.align_to_station", "按车站对齐"}, {"button.jump", "跳转"},
            {"frame.controls", "控制"}, {"frame.console", "控制台"}, {"frame.file_structure_diagram", "文件结构图"}, {"frame.text_preview", "文本预览"}, {"frame.plots", "2D视图"}, {"frame.othertracks", "其他轨道"}, {"frame.station_list", "车站列表"}, {"frame.station_positions", "车站位置"}, {"frame.station_definitions", "车站定义"},
            {"frame.structures", "地图布景列表"}, {"frame.structures_put_between", "地图布景列表(Putbetween)"}, {"frame.structure_models", "布景模型列表"}, {"frame.sound_list", "音效文件列表"}, {"frame.sound_3d_list", "3D音效文件列表"}, {"frame.repeaters", "连续布景列表"}, {"frame.signal_aspects", "信号现示列表"}, {"frame.signals", "地图信号列表"}, {"frame.beacons", "应答器列表"}, {"frame.irregularities", "轨道变位列表"}, {"frame.adhesions", "粘着特性变化点列表"}, {"frame.speed_limits", "限速点列表"}, {"frame.cab_illuminance", "驾驶台亮度变化点列表"}, {"frame.fogs", "雾效果变化点列表"}, {"frame.legacy_fogs", "旧式雾效果变化点列表"}, {"frame.lighting", "光照效果"}, {"frame.draw_distances", "绘制距离变化点列表"}, {"frame.aux_info", "辅助信息"}, {"frame.model_preview", "3D-模型预览"}, {"frame.scene_preview", "3D-场景预览"},
            {"label.light_statement_missing", "当前地图中无此语句"},
            {"frame.chart_visibility", "图表显示"}, {"frame.grid", "网格"}, {"frame.mode", "模式"}, {"frame.bgimage", "背景图"},
            {"aux.station", "车站"}, {"aux.scenery", "布景"}, {"aux.track_geometry", "轨道几何"}, {"aux.signal", "信号"}, {"aux.sound", "音效"}, {"aux.effects", "效果"}, {"aux.scene_3d", "3D场景"}, {"aux.other", "其它"},
            {"column.file_name", "文件名"}, {"column.show", "显示"}, {"column.key", "键"}, {"column.from", "起点"}, {"column.to", "终点"}, {"column.color", "颜色"},
            {"find.partial_match", "部分匹配"}, {"find.exact_match", "完全匹配"},
            {"chk.station_pos", "车站位置"}, {"chk.station_name", "车站名"}, {"chk.station_mileage", "车站里程"},
            {"chk.gradient_pos", "坡度变化点"}, {"chk.gradient_val", "坡度值"}, {"chk.curve_val", "曲线半径"},
            {"chk.prof_othert", "纵断面其他轨道"}, {"chk.speedlimit", "限速"}, {"chk.irregularity_markers", "轨道变位变化点"}, {"chk.beacon_markers", "应答器位置"}, {"chk.pretrain_markers", "先行列车通过点"}, {"chk.other_train_paths", "他列车路径"}, {"chk.adhesion_markers", "粘着特性变化点"}, {"chk.cab_illuminance_markers", "驾驶台亮度变化点"}, {"chk.fog_markers", "雾效果变化点"}, {"chk.draw_distance_markers", "绘制距离变化点"}, {"chk.scene_owntrack_markers", "自轨道标记"}, {"chk.scene_current_position_on_plan", "平面图上显示当前位置"}, {"chk.console_window", "控制台窗口"},
            {"chk.view_2d_window", "2D视图窗口"}, {"chk.select_all", "全选"}, {"chk.edit_mode", "编辑模式"},
            {"chk.edit_mode_warning_dont_show", "不再显示"},
            {"chk.gradient_graph", "纵断面图"}, {"chk.curve_graph", "曲线半径图"}, {"chk.bgimg_show", "显示"},
            {"grid.fixed", "固定"}, {"grid.movable", "可移动"}, {"grid.none", "无"},
            {"mode.pan", "移动"}, {"mode.select", "选择"}, {"mode.mileage_select", "里程选择"}, {"mode.measure", "测量"}, {"label.minimum", "最小值"}, {"label.maximum", "最大值"}, {"label.interval", "间隔"}, {"label.station_jump", "车站跳转"}, {"label.distance_jump", "跳转到里程(m)"}, {"label.source_file", "源文件"}, {"label.source_position", "位置"}, {"label.source_distance_string", "原始距离字符串"}, {"label.raw_statement", "原始语句"}, {"label.source_section", "源码区段"}, {"label.include_context", "Include 上下文"}, {"label.pending_insertion", "将要插入的语句"},
            {"canvas.plan", "平面图"}, {"canvas.profile", "纵断面 / 标高"}, {"canvas.radius", "曲线半径"},
            {"plot.profile", "纵断面"}, {"plot.radius", "曲线半径"}, {"plot.level", "水平"}, {"unit.m", "m"},
            {"info.mileage", "里程"}, {"info.elevation", "标高"}, {"info.gradient", "坡度"}, {"info.radius", "曲线半径"},
            {"info.speedlimit", "限速"}, {"info.no_limit", "无"},
            {"hint.pick_bg_station", "双击背景图上的车站位置"}, {"hint.distance_choose_boundary", "请选择下方由解析器确认并高亮的语句边界。"},
            {"label.bgimg_x", "X (m)"}, {"label.bgimg_y", "Y (m)"}, {"label.bgimg_width", "宽度 (m)"},
            {"label.bgimg_height", "高度 (m)"}, {"label.bgimg_rotation", "旋转角度 (度)"}, {"label.bgimg_brightness", "亮度 (%)"},
            {"label.font_size", "文字大小"}, {"label.ui_component_size", "界面组件大小"}, {"label.station_marker_size", "标记尺寸"}, {"label.own_track_line_width", "自轨道标线宽度"}, {"label.other_track_line_width", "他轨道标线宽度"}, {"label.chart_marker_line_width", "图表标线宽度"}, {"label.background_grid_line_width", "背景网格线宽度"}, {"label.scene_auto_load_on_map_open", "打开地图时自动加载场景预览"}, {"label.scene_fog_effect", "雾效果"}, {"label.scene_map_draw_distance", "绘制距离根据地图语句调整"}, {"label.scene_draw_distance", "绘制距离"}, {"label.scene_edit_component_size", "编辑用组件尺寸"}, {"label.scene_camera_speed", "相机移动速度"}, {"label.scene_performance_warning", "性能警告"}, {"label.scene_instance_warning_threshold", "警告标准"}, {"label.scene_instance_critical_warning_threshold", "严重警告标准"}, {"label.ui_theme_color", "界面主题色"},
            {"label.font_size_current", "文字大小："}, {"label.ui_component_size_current", "组件大小："}, {"label.ui_theme_color_current", "主题色："}, {"label.font_size_preview", "预览文字"},
            {"label.quick_colors", "快捷颜色"}, {"color.white", "纯白"}, {"color.black", "纯黑"}, {"color.gray", "灰色"}, {"color.blue", "纯蓝色"}, {"color.green", "纯绿色"},
            {"status.edit.repeater_end_before_begin", "Repeater的结束里程不能小于开始里程"}, {"status.edit.transition_start_after_distance", "缓和曲线起点里程不能大于对应语句里程"},
            {"status.no_map", "未加载地图"}, {"status.resource_list_no_map", "当前未加载地图"}, {"status.resource_list_not_specified", "当前地图中未指定{resource_list}"}, {"status.loading", "加载中..."}, {"status.scene_loading", "正在加载……"}, {"status.ready", "就绪"}, {"status.text_preview_load_failed", "无法加载文本预览。"}, {"status.distance_no_boundaries", "解析器未返回可选的语句边界。"}, {"status.edit.pending", "待保存更改"}, {"status.edit.pending_delete", "待删除"}, {"status.edit.reverted", "已撤销"}, {"status.edit.no_changes", "没有更改"}, {"status.edit.required_field", "必填项为空"}, {"status.edit.invalid_number", "数字无效"}, {"status.edit.repeater_key_conflict", "连续布景 key 与其它区间重叠"}, {"status.edit.other_track_key_conflict", "他轨道 trackKey 已存在"}, {"status.edit.applying", "正在应用更改……"}, {"status.edit.reverting", "正在还原编辑..."}, {"status.edit.saving", "正在保存……"}, {"status.edit.applied_to_preview", "已应用到预览"}, {"status.edit.saved", "已保存"}, {"status.edit.mode_enabled", "编辑模式已启用"}, {"status.edit.mode_disabled", "编辑模式已关闭"}, {"status.edit.loading_metadata", "正在加载编辑元数据..."}, {"status.edit.disable_blocked_unsaved", "关闭编辑模式前请先保存或撤销待保存更改。"}, {"status.edit.distance_resolution_required", "需要选择源码插入位置"}, {"status.edit.distance_resolution_cancelled", "已取消源码插入位置选择"},
            {"status.edit.apply_station_list_before_save", "保存前请先应用车站定义表格的更改。"},
            {"status.find.no_match", "未找到匹配的字符"}, {"status.find.match", "查找到（{current}/{total}）"}, {"status.unused_structure_models.match", "找到未使用模型（{unused}/{total}）"}, {"status.unused_structure_models.no_match", "没有找到未使用模型"}, {"status.unused_signal_aspects.match", "找到未使用信号现示（{unused}/{total}）"}, {"status.unused_signal_aspects.no_match", "没有找到未使用信号现示"}, {"status.unused_sound_files.match", "找到未使用音效（{unused}/{total}）"}, {"status.unused_sound_files.no_match", "没有找到未使用音效"}, {"status.unused_sound_3d_files.match", "找到未使用3D音效（{unused}/{total}）"}, {"status.unused_sound_3d_files.no_match", "没有找到未使用3D音效"},
            {"dialog.edit_mode_warning_title", "启用编辑模式"}, {"dialog.resource_list_file_change_title", "更换资源列表文件"},
            {"dialog.resource_list_file_change_message", "这将放弃该列表中未应用和未保存的旧文件内容修改。是否继续？"},
            {"dialog.edit_mode_warning_message", "是否启用编辑模式？\n编辑属于不稳定的测试性功能，可能会对地图文件产生破坏性更改。建议事先备份地图文件，或使用 Git 等版本控制工具管理地图文件。"},
            {"dialog.other_track_rename_title", "重命名其他轨道"}, {"label.track_key", "trackKey"},
            {"dialog.repeater_change_point_insert_title", "插入Repeater变化点"},
            {"dialog.repeater_change_point_insert_message", "当前区间已有同名连续布景，语句将作为变化点插入，是否继续？"},
            {"dialog.repeater_extra_end_title", "Repeater结束语句已存在"},
            {"dialog.repeater_extra_end_message", "同名连续布景已有结束语句，如需调整请在编辑功能中直接编辑结束位置"},
            {"dialog.ui_settings", "用户界面设置"}, {"dialog.canvas_element_sizes", "画布元素尺寸"}, {"dialog.canvas_3d_settings", "3D画布设置"}, {"dialog.element_properties", "属性/编辑"}, {"dialog.distance_resolution_title", "距离语句移动位置"}, {"dialog.distance_resolution_message", "无法自动确定语句移动位置，是否手动选择？"}, {"dialog.distance_expression_title", "距离源字符串"}, {"dialog.distance_variable_message", "变量[{variable}]在上下文中存在多个值，是否手动编辑源字符串？"}, {"dialog.reload_unsaved_title", "重新加载"}, {"dialog.reload_unsaved_message", "有未保存的更改，确认是否重新加载？"}, {"dialog.revert_all_edits_title", "撤销全部改动"}, {"dialog.revert_all_edits_message", "撤销所有未保存的改动吗？这会将内存中的地图恢复到上次保存后的状态，且无法重做。"}, {"dialog.unsaved_changes_title", "未保存的更改"}, {"dialog.unsaved_exit_message", "有未保存的更改，确定要退出吗？"}, {"dialog.unsaved_close_edit_message", "有未保存的更改，确定要关闭编辑吗？"}, {"dialog.bgimage_adjust", "调整背景图"}, {"dialog.align_to_station", "按车站对齐背景图"}, {"button.pick_on_bg", "在平面图选点"}, {"button.pick_on_bg_ok", "已选点"},
            {"dialog.apply_station_list_before_save", "保存前请先应用车站定义表格中的更改。"},
            {"dialog.open_document_unsaved_title", "打开文件"}, {"dialog.open_document_unsaved_message", "有未保存的更改。要打开其它文件并丢弃这些更改吗？"},
            {"about.text", "komapedit\nVersion 0.7.9\nCopyright © 2026 Sapporo_ningyo\n基于 kobushi-trackviewer\nCopyright © 2021-2024 konawasabi\n许可证：Apache License 2.0\n第三方：Dear ImGui (MIT)、ImPlot (MIT)\n详见 LICENSE、NOTICE 和 THIRD_PARTY_NOTICES.md"}
        };
        ja = {
            {"menu.import_submap", "サブマップをインポート..."},
            {"menu.new_submap", "サブマップを新規作成..."},
            {"dialog.create_include_file", "サブマップファイルを新規作成"},
            {"status.edit.include_create_failed", "サブマップファイルを作成できません。"},
            {"frame.sections", "閉そく一覧"},
            {"frame.section_begins", "閉そく開始位置"},
            {"frame.section_speed_limits", "閉そく速度制限"},
            {"frame.variables", "変数一覧"},
            {"frame.scenario_file", "シナリオファイル"},
            {"menu.map_info.sections", "閉そく"},
            {"menu.map_info.variables", "変数"},
            {"menu.map_info.scenario_file", "シナリオファイル"},
            {"menu.locate_in_section_list", "閉そく一覧で表示"},
            {"chk.section_markers", "閉そくマーカー"},
            {"label.source_path", "ソースパス"},
            {"label.enable_time", "有効時刻"},
            {"column.variable", "変数"},
            {"column.value", "代入値"},
            {"scene.route_info.speed_limit", "速度制限:"},
            {"scene.route_info.signal", "信号:"},
            {"dialog.coordinate_offset_discard_title", "座標オフセットの削除"},
            {"dialog.coordinate_offset_discard_message", "このストラクチャーの座標オフセットはすべて破棄されます。続行しますか？"},
            {"label.repeater_end_source", "終了位置のソース："}, {"value.none", "なし"}, {"value.own_track", "(自軌道)"},
            {"value.tilt.always_level", "常に水平"}, {"value.tilt.follow_gradient", "勾配に連動"}, {"value.tilt.follow_cant", "カントに連動"}, {"value.tilt.follow_gradient_and_cant", "勾配とカントに連動"},
            {"value.door.open_left", "左側ドアを開く"}, {"value.door.do_not_open", "ドアを開かない"}, {"value.door.open_right", "右側ドアを開く"},
            {"status.transition_unpaired", "この BeginTransition に対応する Begin/End がないため、編集または削除できません。"},
            {"label.repeater_structure_keys", "構造物キー"},
            {"label.section_parameters", "パラメーター"},
            {"status.repeater_multiple_begins", "この Repeater には複数の Begin 文があります。"},
            {"button.add_repeater_end_position", "終了位置を追加"},
            {"button.insert_repeater_change_point", "変化点を挿入"},
            {"status.map_loading", "マップを読み込み中..."}, {"status.map_loaded", "マップの読み込みが完了しました"}, {"status.map_load_failed", "マップの読み込みに失敗しました"},
            {"status.scene_preview_loading", "3Dシーンプレビューを読み込み中..."}, {"status.scene_preview_loaded", "3Dシーンプレビューの読み込みが完了しました"}, {"status.scene_preview_failed", "3Dシーンプレビューの読み込みに失敗しました"}, {"status.scene_preview_stopped", "3Dシーンプレビューを停止しました"},
            {"status.no_errors_warnings", "エラーまたは警告はありません"}, {"frame.errors_warnings", "エラーと警告"},
            {"scene.route_info.straight", "直線"}, {"scene.route_info.interpolate_unsupported", "補間（未対応）"}, {"scene.route_info.next_station", "次駅："}, {"scene.route_info.no_station_ahead", "前方に駅はありません"},
            {"dialog.distance_expression_message", "距離のソース文字列を手動で編集しますか？"},
            {"dialog.signal_full_form_convert_title", "Signal.Put の変換"}, {"dialog.signal_full_form_convert_message", "この信号機は短い形式の Signal.Put を使用しています。Z、回転、傾斜、またはスパンを編集する前に完全な形式へ変換しますか？"},
            {"dialog.structure_z_rebase_title", "距離の再設定"}, {"dialog.structure_z_rebase_message", "現在のモデルの Z 軸オフセットが 5 m を超えています。距離を再設定しますか？"},
            {"app.title", "komapedit"},
            {"menu.map_info.other_trains", "他列車"},
            {"frame.other_trains", "他列車リスト"},
            {"frame.other_train_definitions", "定義"},
            {"frame.other_train_stops", "停止位置"},
            {"frame.structure_put", "Put"},
            {"frame.structure_put_between", "PutBetween"},
            {"menu.locate_in_other_train_stop_list", "他列車停止位置リストへ移動"},
            {"frame.map_sounds", "マップサウンドリスト"},
            {"frame.map_sound_3d", "固定音源サウンド"},
            {"button.map_sound_list", "マップサウンドリスト"},
            {"button.map_sound_3d_list", "マップ3Dサウンドリスト"},
            {"chk.map_sound_markers", "サウンド再生位置"},
            {"chk.map_sound_3d_markers", "固定サウンド位置"},
            {"menu.locate_in_map_sound_list", "マップサウンドリストへ移動"},
            {"menu.locate_in_map_sound_3d_list", "マップ3Dサウンドリストへ移動"},
            {"frame.rolling_noises", "走行音変化点リスト"},
            {"chk.rolling_noise_markers", "走行音変化点"},
            {"menu.locate_in_rolling_noise_list", "走行音変化点リストへ移動"},
            {"frame.flange_noises", "フランジきしり音変化点リスト"},
            {"chk.flange_noise_markers", "フランジきしり音変化点"},
            {"menu.locate_in_flange_noise_list", "フランジきしり音変化点リストへ移動"},
            {"frame.joint_noises", "分岐器通過音再生点リスト"},
            {"chk.joint_noise_markers", "分岐器通過音再生点"},
            {"menu.locate_in_joint_noise_list", "分岐器通過音再生点リストへ移動"},
            {"frame.backgrounds", "背景変化点リスト"},
            {"chk.background_markers", "背景変化点"},
            {"menu.locate_in_background_list", "背景変化点リストへ移動"},
            {"menu.file", "ファイル"}, {"menu.options", "オプション"}, {"menu.map_info", "マップ情報リスト"}, {"menu.view_2d", "2Dプロット"}, {"menu.lang", "言語"}, {"menu.help", "ヘルプ"},
            {"menu.map_info.othertracks", "他軌道"}, {"menu.map_info.station", "停車場"}, {"menu.map_info.signal_aspects", "信号現示"}, {"menu.map_info.signals", "マップ信号"}, {"menu.map_info.beacons", "地上子"},
            {"menu.map_info.structures", "マップストラクチャー"}, {"menu.map_info.structures_put_between", "マップストラクチャー(PutBetween)"}, {"menu.map_info.structure_models", "ストラクチャーモデル"}, {"menu.map_info.sound_files", "サウンドファイル"}, {"menu.map_info.sound_3d_files", "3Dサウンドファイル"}, {"menu.map_info.map_sounds", "マップサウンド"},
            {"menu.map_info.map_sound_3d", "マップ3Dサウンド"}, {"menu.map_info.repeaters", "連続ストラクチャー"}, {"menu.map_info.irregularities", "軌道変位"}, {"menu.map_info.rolling_noises", "走行音変化点"}, {"menu.map_info.flange_noises", "フランジきしり音変化点"},
            {"menu.map_info.joint_noises", "分岐器通過音再生点"}, {"menu.map_info.backgrounds", "背景変化点"}, {"menu.map_info.adhesions", "粘着特性変化点"}, {"menu.map_info.speed_limits", "速度制限点"}, {"menu.map_info.cab_illuminance", "運転台明るさ変化点"}, {"menu.map_info.fogs", "霧効果変化点"}, {"menu.map_info.legacy_fogs", "レガシー霧効果変化点"}, {"menu.map_info.lighting", "照明"}, {"menu.map_info.draw_distances", "描画距離変化点"},
            {"menu.open", "開く..."}, {"menu.recent_maps", "最近開いたマップ"}, {"menu.none", "なし"}, {"menu.clear_recent_maps", "リストをクリア"}, {"menu.reload", "再読込"}, {"menu.export_csv", "CSV 出力..."}, {"menu.exit", "終了"},
            {"menu.controlpoints", "制御点間隔..."}, {"menu.plotlimit", "描画範囲..."}, {"menu.ui_settings", "UI設定..."}, {"menu.canvas_2d_settings", "2Dキャンバス設定"}, {"menu.canvas_element_sizes", "キャンバス要素サイズ"}, {"menu.canvas_3d_settings", "3Dキャンバス設定"}, {"menu.about", "このアプリについて"},
            {"menu.online_docs", "オンラインドキュメント"}, {"menu.report_bugs", "不具合を報告"}, {"menu.open_in_explorer", "エクスプローラーで開く"}, {"menu.select_file", "ファイルを選択"}, {"menu.preview_text", "テキストをプレビュー"}, {"menu.unreference_include", "Include の参照を解除"}, {"menu.change_include_file", "参照ファイルを変更..."}, {"menu.change_file", "ファイルを変更..."}, {"menu.locate_on_plan", "平面図へ移動"}, {"menu.locate_in_scene_preview", "3Dシーンプレビューへ移動"}, {"menu.locate_in_structure_list", "ストラクチャーリストへ移動"}, {"menu.locate_in_structure_put_between_list", "ストラクチャーリスト(PutBetween)へ移動"}, {"menu.locate_in_repeater_list", "連続ストラクチャーリストへ移動"}, {"menu.repeater_delete_all", "すべて削除"}, {"menu.repeater_delete_change_point", "対応する変化点を削除"}, {"menu.repeater_trim_to_change_point", "変化点までトリム"}, {"menu.repeater_start_from_change_point", "変化点から開始"}, {"menu.jump_to_repeater_start_position", "開始位置へジャンプ"}, {"menu.jump_to_repeater_end_or_change_position", "終了/変更位置へジャンプ"}, {"menu.locate_in_signal_list", "マップ信号リストへ移動"}, {"menu.locate_in_beacon_list", "地上子リストへ移動"}, {"menu.locate_in_irregularity_list", "軌道変位リストへ移動"}, {"menu.locate_in_adhesion_list", "粘着特性変化点リストへ移動"}, {"menu.locate_in_cab_illuminance_list", "運転台明るさ変化点リストへ移動"}, {"menu.locate_in_fog_list", "霧効果変化点リストへ移動"}, {"menu.locate_in_legacy_fog_list", "レガシー霧効果変化点リストへ移動"}, {"menu.locate_in_draw_distance_list", "描画距離へ移動"}, {"menu.locate_in_speed_limit_list", "速度制限点リストで表示"},
            {"menu.view_3d", "3Dビュー"}, {"menu.structure_model_preview", "ストラクチャーモデルプレビュー"}, {"menu.scene_preview", "3Dシーンプレビュー"}, {"menu.preview_model", "モデルをプレビュー"}, {"menu.switch_signal_aspect", "信号現示を切替"}, {"menu.find_in_structure_models", "ストラクチャーモデルリストで検索"}, {"menu.find_in_signal_aspects", "信号現示リストで検索"}, {"menu.find_in_sound_files", "サウンドファイルリストで検索"}, {"menu.find_in_sound_3d_files", "3Dサウンドファイルリストで検索"},
            {"menu.use_this_model", "このモデルを使用"}, {"menu.use_this_sound", "このサウンドを使用"},
            {"button.open", "開く"}, {"button.reload", "再読込"}, {"button.reload_geometry", "線形を再読込"}, {"button.reload_scene_models", "再読込（モデル）"}, {"button.export_csv", "CSV 出力"},
            {"button.structure_list", "マップストラクチャーリスト"}, {"button.repeater_list", "連続ストラクチャーリスト"},
            {"button.apply", "適用"}, {"button.apply_jump_to_edit", "適用して編集"}, {"button.new", "新規"}, {"button.reset", "リセット"}, {"button.revert", "元に戻す"}, {"button.save", "保存"}, {"button.delete", "削除"}, {"button.ok", "OK"}, {"button.cancel", "キャンセル"}, {"button.clear", "クリア"}, {"button.copy", "コピー"}, {"button.close", "閉じる"}, {"button.previous", "前へ"}, {"button.next", "次へ"}, {"button.confirm_reuse", "そのまま再利用"}, {"button.manual_select", "手動で選択"},
            {"button.confirm_and_load", "確認して読み込む"},
            {"button.add_coordinate_offsets", "座標オフセットを追加"}, {"button.remove_coordinate_offsets", "座標オフセットを削除"},
            {"button.add_map_element", "マップ要素を追加"}, {"menu.add_map_element_at_current_mileage", "現在のキロ程にマップ要素を追加"}, {"dialog.new_element_wizard", "マップ要素追加ウィザード"}, {"label.new_element_target_file", "書き込み先ソースファイル"}, {"label.transition_start", "緩和曲線開始距離程"},
            {"menu.new_file", "新規作成..."}, {"dialog.new_file_wizard", "新規ファイルウィザード"}, {"new_file.category.presets", "プリセット"}, {"new_file.category.map", "マップ"}, {"new_file.category.resource_lists", "マップリソースリスト"},
            {"new_file.usage.map", "空白の BveTs Map 2.02 ソースファイルを作成します。"}, {"new_file.usage.structure", "マップストラクチャー用の空白 Structure List ファイルを作成します。"}, {"new_file.usage.signal", "信号定義用の空白 Signal Aspects List ファイルを作成します。"}, {"new_file.usage.sound", "列車音と環境音用の空白 Sound List ファイルを作成します。"}, {"new_file.usage.sound3d", "三次元音用の空白 Sound List ファイルを作成します。"}, {"new_file.usage.station", "駅定義用の空白 Station List ファイルを作成します。"},
            {"label.new_file_name", "ファイル名"}, {"label.new_file_directory", "ファイルパス"}, {"label.new_file_reference", "次のファイルに参照を追加"}, {"button.select_directory", "ディレクトリを選択"}, {"button.confirm", "確認"}, {"dialog.select_export_folder", "エクスポート先フォルダーを選択"}, {"dialog.select_new_file_directory", "ファイルディレクトリを選択"},
            {"status.new_file.invalid_path", "有効なファイル名と既存のディレクトリを入力してください。"}, {"status.new_file.create_failed", "新規ファイルを作成できませんでした。"}, {"status.new_file.created", "新規ファイルを作成しました。"}, {"status.new_file.reference_requires_edit", "参照を追加するには編集モードが必要です。"}, {"status.new_file.resource_list_already_loaded", "このリソースリスト種別は既に読み込まれています。"}, {"status.new_file.reference_failed", "ファイルは作成されましたが、参照をステージできませんでした。"},
            {"button.import_file", "ファイルをインポート"}, {"button.new_or_import_file", "新規作成またはファイルをインポート"}, {"button.add_row", "行を追加"},
            {"resource_list.name.station", "駅リスト"}, {"resource_list.name.structure", "ストラクチャーモデルリスト"}, {"resource_list.name.signal", "信号現示リスト"}, {"resource_list.name.sound", "サウンドファイルリスト"}, {"resource_list.name.sound3d", "固定音源サウンドリスト"},
            {"status.new_file.reused", "既存のファイルを再利用しました。"}, {"status.new_file.resource_list_already_present", "現在のマップには既に{resource_list}があります。置き換えるには、対応するリスト上部の「ファイルパス」を右クリックしてください。"},
            {"new_element.usage.structure.put", "指定位置にストラクチャーを配置します。"},
            {"new_element.usage.structure.put0", "座標オフセットなしでストラクチャーを配置します。傾き方とスパンのみが設定されます。"},
            {"new_element.usage.repeater.begin", "Repeater.Begin、Repeater.End、または両方を追加します。Begin は座標オフセットを使用します。"},
            {"new_element.usage.repeater.begin0", "Repeater.Begin0、Repeater.End、または両方を追加します。Begin0 は座標オフセットを使用しません。"},
            {"chk.new_element_repeater_add_begin", "Beginを追加"}, {"chk.new_element_repeater_add_end", "Endを追加"}, {"chk.new_element_include_parameter", "この引数を含める"},
            {"new_element.usage.curve", "対応している曲線の開始位置、終了位置、または両方を追加します。"},
            {"new_element.usage.gradient", "対応している勾配の開始位置、終了位置、または両方を追加します。"},
            {"chk.new_element_add_start", "開始位置を追加"}, {"chk.new_element_add_end", "終了位置を追加"},
            {"chk.new_element_own_track_add_transition", "緩和曲線開始点を追加"}, {"chk.new_element_add_parameter", "この引数を追加"},
            {"new_element.usage.structure.put_between", "2つの軌道の間にストラクチャーを配置し、軌道間の距離に応じて変形させます。"},
            {"new_element.usage.station.put", "指定距離に列車の停止位置を設定します。"},
            {"new_element.usage.signal.put", "指定位置・閉塞区間に信号機を配置します。"},
            {"new_element.usage.speedlimit.begin", "指定距離・速度で速度制限を開始します。"},
            {"new_element.usage.speedlimit.end", "指定距離で速度制限を終了します。"},
            {"new_element.usage.section.begin", "指定した信号インデックスで新しい閉そくを開始します。"},
            {"new_element.usage.section.beginnew", "Section.Begin の旧式形式です。指定した信号インデックスで新しい閉そくを開始します。"},
            {"new_element.usage.section.setspeedlimit", "指定距離で信号現示の許容速度を設定します。"},
            {"new_element.usage.section.signal_speedlimit", "Section.SetSpeedLimit の旧式形式です。指定距離で信号現示の許容速度を設定します。"},
            {"new_element.usage.irregularity.change", "指定距離以降の軌道変位を設定します。"},
            {"new_element.usage.other_track.position", "現在距離程の他軌道位置を設定します（X/Y Interpolate と同等）。"},
            {"new_element.usage.other_track.x_interpolate", "現在距離程の他軌道 X 座標を設定し、前の X 点との間を補間します。"},
            {"new_element.usage.other_track.y_interpolate", "現在距離程の他軌道 Y 座標を設定し、前の Y 点との間を補間します。"},
            {"new_element.usage.other_track.cant_set_gauge", "現在距離程以降の他軌道軌間を設定します（カントを角度に換算）。"},
            {"new_element.usage.other_track.cant_set_center", "現在距離程以降の他軌道カントの回転中心を設定します。"},
            {"new_element.usage.other_track.cant_set_function", "現在距離程以降の他軌道カント逓減関数を設定します。"},
            {"new_element.usage.other_track.cant_begin_transition", "現在距離程から他軌道カントの逓減を開始します。"},
            {"new_element.usage.other_track.cant_begin", "現在距離程でカント逓減を終了し、一定カントを開始します。"},
            {"new_element.usage.other_track.cant_end", "現在距離程で他軌道のカントを終了します。"},
            {"new_element.usage.other_track.cant_interpolate", "現在距離程の他軌道カントを設定し、前のカント点との間を補間します。"},
            {"new_element.usage.beacon.put", "指定距離に地上子の送信イベントを定義します。"},
            {"new_element.usage.map_sound.play", "指定距離を通過するときにサウンドを1回再生します。"},
            {"new_element.usage.map_sound3d.put", "指定距離に地上に固定された3D音源を設置します。サウンドは連続再生されます。"},
            {"new_element.usage.rolling_noise.change", "指定距離以降の走行音を設定します。"},
            {"new_element.usage.flange_noise.change", "指定距離以降のフランジきしり音を設定します。"},
            {"new_element.usage.joint_noise.play", "指定距離を通過するときに走行速度に応じて分岐器通過音を再生します。"},
            {"new_element.usage.background.change", "指定距離で背景を変更します。"},
            {"new_element.usage.adhesion.change", "指定距離以降の車輪・レール間の粘着特性を設定します。"},
            {"new_element.usage.cab_illuminance.set", "CabIlluminance.Interpolate の旧式形式です。指定距離の運転台の明るさを設定し、点の間を線形補間します。"},
            {"new_element.usage.cab_illuminance.interpolate", "指定距離の運転台の明るさを設定し、点の間を線形補間します。"},
            {"new_element.usage.fog.set", "Fog.Interpolate の旧式形式です。指定距離の霧効果を設定し、点の間を線形補間します。"},
            {"new_element.usage.fog.interpolate", "指定距離の霧効果を設定し、点の間を線形補間します。"},
            {"new_element.usage.light.ambient", "距離程 0 で環境光の色を設定します。RGB の各成分は 0 から 1 の範囲で、論理マップ内には Light.Ambient 宣言を 1 つだけ記述できます。"},
            {"new_element.usage.light.diffuse", "距離程 0 で平行光の色を設定します。RGB の各成分は 0 から 1 の範囲で、論理マップ内には Light.Diffuse 宣言を 1 つだけ記述できます。"},
            {"new_element.usage.light.direction", "距離程 0 で平行光の方向を設定します。論理マップ内には Light.Direction 宣言を 1 つだけ記述できます。"},
            {"new_element.usage.draw_distance.change", "指定距離以降の風景描画距離を設定します。"},
            {"status.edit.no_distance_source", "編集可能なマップソースファイルがありません。"},
            {"status.new_file.no_reference_target", "参照できる編集ソースファイルがありません。"},
            {"context.station_list.insert_above", "上に行を追加"}, {"context.station_list.insert_below", "下に行を追加"}, {"context.station_list.move_up", "行全体を上へ移動"}, {"context.station_list.move_down", "行全体を下へ移動"}, {"context.station_list.clear_cell", "セルをクリア"}, {"context.station_list.delete_row", "行全体を削除"}, {"context.other_track.rename", "名前を変更"},
            {"context.editable_list.insert_above", "上に行を追加"}, {"context.editable_list.insert_below", "下に行を追加"}, {"context.editable_list.move_up", "行全体を上へ移動"}, {"context.editable_list.move_down", "行全体を下へ移動"}, {"context.editable_list.clear_cell", "セルをクリア"}, {"context.editable_list.delete_row", "行全体を削除"}, {"context.signal_aspect.add_glare", "グレアを追加"}, {"context.signal_aspect.delete_glare", "グレアを削除"}, {"context.plan_marker.structure", "ストラクチャー"}, {"context.plan_marker.repeater", "連続ストラクチャー"}, {"context.plan_marker.signal", "マップ信号"}, {"context.plan_marker.other_train_stop", "他列車停止位置"}, {"context.plan_marker.other_track_change", "他軌道変化点"},
            {"dialog.select_resource_file", "リソースファイルを選択"}, {"dialog.select_include_file", "読み込むマップファイルを選択"}, {"dialog.select_resource_list_file", "リソースリストファイルを選択"}, {"dialog.filter.audio_files", "サウンドファイル"}, {"dialog.filter.model_files", "モデルファイル"}, {"dialog.filter.all_files", "すべてのファイル"}, {"dialog.filter.map_files", "BVE マップ/シナリオファイル"}, {"dialog.filter.resource_list_files", "リソースリストファイル"}, {"dialog.scenario_route_select_title", "シナリオに複数のマップ候補があります。読み込むものを1つ選択してください"}, {"status.edit.relative_path_fallback", "相対パスを生成できなかったため、絶対パスを使用しました。"}, {"status.edit.not_structure_list_file", "このファイルはストラクチャーリストファイルではありません。"}, {"status.edit.not_signal_aspect_list_file", "このファイルは信号現示リストファイルではありません。"}, {"status.edit.not_sound_list_file", "このファイルはサウンドリストファイルではありません。"},
            {"status.edit.not_station_list_file", "このファイルは停車場リストファイルではありません。"},
            {"status.edit.apply_list_before_save", "保存する前にすべてのリストテーブルの変更を適用してください。"}, {"dialog.apply_list_before_save", "保存する前にすべてのリストテーブルの変更を適用してください。"},
            {"button.save_changes_and_exit", "変更を保存して終了"}, {"button.discard_changes_and_exit", "変更を破棄して終了"}, {"button.save_changes_and_close_edit", "変更を保存して編集を終了"}, {"button.discard_changes_and_close_edit", "変更を破棄して編集を終了"},
            {"button.model_list", "モデルリスト"}, {"button.start_scene_preview", "3Dシーンプレビューを開始"}, {"button.background_color", "背景色"}, {"button.find", "検索"}, {"button.find_unused_structure_models", "未使用モデルを検索"}, {"button.find_unused_signal_aspects", "未使用信号現示を検索"}, {"button.find_unused_sound_files", "未使用サウンドを検索"}, {"button.find_unused_sound_3d_files", "未使用3Dサウンドを検索"},
            {"button.import_bg", "インポート"}, {"button.adjust_bg", "調整"}, {"button.align_to_station", "駅に合わせる"}, {"button.jump", "ジャンプ"},
            {"frame.controls", "コントロール"}, {"frame.console", "コンソール"}, {"frame.file_structure_diagram", "ファイル構成図"}, {"frame.text_preview", "テキストプレビュー"}, {"frame.plots", "2Dビュー"}, {"frame.othertracks", "他軌道"}, {"frame.station_list", "停車場リスト"}, {"frame.station_positions", "停車場位置"}, {"frame.station_definitions", "停車場定義"},
            {"frame.structures", "ストラクチャーリスト"}, {"frame.structures_put_between", "ストラクチャーリスト(PutBetween)"}, {"frame.structure_models", "ストラクチャーモデルリスト"}, {"frame.sound_list", "サウンドファイルリスト"}, {"frame.sound_3d_list", "3Dサウンドファイルリスト"}, {"frame.repeaters", "連続ストラクチャーリスト"}, {"frame.signal_aspects", "信号現示リスト"}, {"frame.signals", "マップ信号リスト"}, {"frame.beacons", "地上子リスト"}, {"frame.irregularities", "軌道変位リスト"}, {"frame.adhesions", "粘着特性変化点リスト"}, {"frame.speed_limits", "速度制限点リスト"}, {"frame.cab_illuminance", "運転台明るさ変化点リスト"}, {"frame.fogs", "霧効果変化点リスト"}, {"frame.legacy_fogs", "レガシー霧効果変化点リスト"}, {"frame.lighting", "照明効果"}, {"frame.draw_distances", "描画距離変化点リスト"}, {"frame.aux_info", "補助情報"}, {"frame.model_preview", "3D-モデルプレビュー"}, {"frame.scene_preview", "3D-シーンプレビュー"},
            {"label.light_statement_missing", "このマップにはこのステートメントがありません。"},
            {"frame.chart_visibility", "チャート表示"}, {"frame.grid", "グリッド"}, {"frame.mode", "モード"}, {"frame.bgimage", "背景画像"},
            {"aux.station", "駅"}, {"aux.scenery", "ストラクチャー"}, {"aux.track_geometry", "軌道幾何"}, {"aux.signal", "信号"}, {"aux.sound", "サウンド"}, {"aux.effects", "効果"}, {"aux.scene_3d", "3Dシーン"}, {"aux.other", "その他"},
            {"column.file_name", "ファイル名"}, {"column.show", "表示"}, {"column.key", "キー"}, {"column.from", "始点"}, {"column.to", "終点"}, {"column.color", "色"},
            {"find.partial_match", "部分一致"}, {"find.exact_match", "完全一致"},
            {"chk.station_pos", "駅位置"}, {"chk.station_name", "駅名"}, {"chk.station_mileage", "駅キロ程"},
            {"chk.gradient_pos", "勾配変化点"}, {"chk.gradient_val", "勾配値"}, {"chk.curve_val", "曲線半径"},
            {"chk.prof_othert", "縦断面の他軌道"}, {"chk.speedlimit", "速度制限"}, {"chk.irregularity_markers", "軌道変位変化点"}, {"chk.beacon_markers", "地上子位置"}, {"chk.pretrain_markers", "先行列車通過点"}, {"chk.other_train_paths", "他列車経路"}, {"chk.adhesion_markers", "粘着特性変化点"}, {"chk.cab_illuminance_markers", "運転台明るさ変化点"}, {"chk.fog_markers", "霧効果変化点"}, {"chk.draw_distance_markers", "描画距離変化点"}, {"chk.scene_owntrack_markers", "自軌道マーカー"}, {"chk.scene_current_position_on_plan", "平面図に現在位置を表示"}, {"chk.console_window", "コンソールウィンドウ"},
            {"chk.view_2d_window", "2Dビューウィンドウ"}, {"chk.select_all", "すべて選択"}, {"chk.edit_mode", "編集モード"},
            {"chk.edit_mode_warning_dont_show", "今後表示しない"},
            {"chk.gradient_graph", "縦断面図"}, {"chk.curve_graph", "曲線半径図"}, {"chk.bgimg_show", "表示"},
            {"grid.fixed", "固定"}, {"grid.movable", "可動"}, {"grid.none", "なし"},
            {"mode.pan", "移動"}, {"mode.select", "選択"}, {"mode.mileage_select", "キロ程選択"}, {"mode.measure", "測定"}, {"label.minimum", "最小値"}, {"label.maximum", "最大値"}, {"label.interval", "間隔"}, {"label.station_jump", "駅ジャンプ"}, {"label.distance_jump", "距離へジャンプ(m)"}, {"label.source_file", "ソース"}, {"label.source_position", "位置"}, {"label.source_distance_string", "元の距離文字列"}, {"label.raw_statement", "元の文"}, {"label.source_section", "ソース区間"}, {"label.include_context", "Include コンテキスト"}, {"label.pending_insertion", "挿入する文"},
            {"canvas.plan", "平面図"}, {"canvas.profile", "縦断面 / 標高"}, {"canvas.radius", "曲線半径"},
            {"plot.profile", "縦断面"}, {"plot.radius", "曲線半径"}, {"plot.level", "水平"}, {"unit.m", "m"},
            {"info.mileage", "キロ程"}, {"info.elevation", "標高"}, {"info.gradient", "勾配"}, {"info.radius", "曲線半径"},
            {"info.speedlimit", "速度制限"}, {"info.no_limit", "なし"},
            {"hint.pick_bg_station", "背景画像上の駅位置をダブルクリック"}, {"hint.distance_choose_boundary", "下で強調表示された、パーサー確認済みの文境界を選択してください。"},
            {"label.bgimg_x", "X (m)"}, {"label.bgimg_y", "Y (m)"}, {"label.bgimg_width", "幅 (m)"},
            {"label.bgimg_height", "高さ (m)"}, {"label.bgimg_rotation", "回転角 (度)"}, {"label.bgimg_brightness", "明るさ (%)"},
            {"label.font_size", "文字サイズ"}, {"label.ui_component_size", "UI部品サイズ"}, {"label.station_marker_size", "マーカーサイズ"}, {"label.own_track_line_width", "自軌道ライン幅"}, {"label.other_track_line_width", "他軌道ライン幅"}, {"label.chart_marker_line_width", "チャートマーカー線幅"}, {"label.background_grid_line_width", "背景グリッド線幅"}, {"label.scene_auto_load_on_map_open", "地図を開くときにシーンプレビューを自動読み込み"}, {"label.scene_fog_effect", "霧効果"}, {"label.scene_map_draw_distance", "マップ文に応じて描画距離を調整"}, {"label.scene_draw_distance", "描画距離"}, {"label.scene_edit_component_size", "編集用コンポーネントサイズ"}, {"label.scene_camera_speed", "カメラ移動速度"}, {"label.scene_performance_warning", "パフォーマンス警告"}, {"label.scene_instance_warning_threshold", "警告しきい値"}, {"label.scene_instance_critical_warning_threshold", "重大警告しきい値"}, {"label.ui_theme_color", "UIテーマカラー"},
            {"label.font_size_current", "文字サイズ："}, {"label.ui_component_size_current", "部品サイズ："}, {"label.ui_theme_color_current", "テーマカラー："}, {"label.font_size_preview", "プレビューテキスト"},
            {"label.quick_colors", "クイック色"}, {"color.white", "白"}, {"color.black", "黒"}, {"color.gray", "グレー"}, {"color.blue", "青"}, {"color.green", "緑"},
            {"status.edit.repeater_end_before_begin", "Repeaterの終了距離は開始距離より前にできません"}, {"status.edit.transition_start_after_distance", "緩和曲線開始点の距離は対応するステートメントの距離を超えることができません"},
            {"status.no_map", "地図が読み込まれていません"}, {"status.resource_list_no_map", "現在マップが読み込まれていません"}, {"status.resource_list_not_specified", "現在のマップには{resource_list}が指定されていません。"}, {"status.loading", "読込中..."}, {"status.scene_loading", "読み込み中..."}, {"status.ready", "準備完了"}, {"status.text_preview_load_failed", "テキストプレビューを読み込めませんでした。"}, {"status.distance_no_boundaries", "選択可能な文境界がパーサーから返されませんでした。"}, {"status.edit.pending", "未保存の変更"}, {"status.edit.pending_delete", "削除待ち"}, {"status.edit.reverted", "元に戻しました"}, {"status.edit.no_changes", "変更なし"}, {"status.edit.required_field", "必須項目が空です"}, {"status.edit.invalid_number", "数値が不正です"}, {"status.edit.repeater_key_conflict", "連続ストラクチャーのキーが別の区間と重複しています"}, {"status.edit.other_track_key_conflict", "他軌道の trackKey は既に存在します"}, {"status.edit.applying", "変更を適用中..."}, {"status.edit.reverting", "編集を元に戻しています..."}, {"status.edit.saving", "保存中..."}, {"status.edit.applied_to_preview", "プレビューに適用しました"}, {"status.edit.saved", "保存しました"}, {"status.edit.mode_enabled", "編集モードを有効にしました"}, {"status.edit.mode_disabled", "編集モードを無効にしました"}, {"status.edit.loading_metadata", "編集メタデータを読み込み中..."}, {"status.edit.disable_blocked_unsaved", "編集モードを無効にする前に変更を保存または元に戻してください。"}, {"status.edit.distance_resolution_required", "ソースの挿入位置を選択してください"}, {"status.edit.distance_resolution_cancelled", "ソースの挿入位置選択をキャンセルしました"},
            {"status.edit.apply_station_list_before_save", "保存する前に駅定義テーブルの変更を適用してください。"},
            {"status.find.no_match", "一致する文字が見つかりません"}, {"status.find.match", "検索結果（{current}/{total}）"}, {"status.unused_structure_models.match", "未使用モデルを検出（{unused}/{total}）"}, {"status.unused_structure_models.no_match", "未使用モデルは見つかりません"}, {"status.unused_signal_aspects.match", "未使用信号現示を検出（{unused}/{total}）"}, {"status.unused_signal_aspects.no_match", "未使用信号現示は見つかりません"}, {"status.unused_sound_files.match", "未使用サウンドを検出（{unused}/{total}）"}, {"status.unused_sound_files.no_match", "未使用サウンドは見つかりません"}, {"status.unused_sound_3d_files.match", "未使用3Dサウンドを検出（{unused}/{total}）"}, {"status.unused_sound_3d_files.no_match", "未使用3Dサウンドは見つかりません"},
            {"dialog.edit_mode_warning_title", "編集モードを有効化"}, {"dialog.resource_list_file_change_title", "リソースリストファイルを変更"},
            {"dialog.resource_list_file_change_message", "このリストの未適用と未保存の変更を破棄します。続行しますか？"},
            {"dialog.edit_mode_warning_message", "編集モードを有効にしますか？\n編集機能は不安定な実験的機能であり、マップファイルに破壊的な変更を加える可能性があります。事前にマップファイルをバックアップするか、Git などのバージョン管理ツールで管理することをお勧めします。"},
            {"dialog.other_track_rename_title", "他軌道名を変更"}, {"label.track_key", "trackKey"},
            {"dialog.repeater_change_point_insert_title", "Repeater変更点を挿入"},
            {"dialog.repeater_change_point_insert_message", "現在の区間には同名の連続ストラクチャーがあります。この文を変更点として挿入します。続行しますか？"},
            {"dialog.repeater_extra_end_title", "Repeater End文が存在します"},
            {"dialog.repeater_extra_end_message", "同名の連続ストラクチャーには既に終了文があります。調整する場合はプロパティ/編集で終了位置を直接編集してください。"},
            {"dialog.ui_settings", "UI設定"}, {"dialog.canvas_element_sizes", "キャンバス要素サイズ"}, {"dialog.canvas_3d_settings", "3Dキャンバス設定"}, {"dialog.element_properties", "プロパティ/編集"}, {"dialog.distance_resolution_title", "距離文の移動位置"}, {"dialog.distance_resolution_message", "文の移動位置を自動で決定できません。手動で選択しますか？"}, {"dialog.distance_expression_title", "距離のソース文字列"}, {"dialog.distance_variable_message", "変数[{variable}]はコンテキスト内で複数の値を持ちます。ソース文字列を手動で編集しますか？"}, {"dialog.reload_unsaved_title", "再読込"}, {"dialog.reload_unsaved_message", "未保存の変更があります。再読込しますか？"}, {"dialog.revert_all_edits_title", "すべての変更を元に戻す"}, {"dialog.revert_all_edits_message", "未保存の変更をすべて元に戻しますか？メモリ上のマップを前回保存時の状態に戻します。この操作はやり直せません。"}, {"dialog.unsaved_changes_title", "未保存の変更"}, {"dialog.unsaved_exit_message", "未保存の変更があります。終了してもよろしいですか？"}, {"dialog.unsaved_close_edit_message", "未保存の変更があります。編集を終了してもよろしいですか？"}, {"dialog.bgimage_adjust", "背景画像の調整"}, {"dialog.align_to_station", "背景画像を駅に合わせる"}, {"button.pick_on_bg", "平面図で駅を選択"}, {"button.pick_on_bg_ok", "選択済み"},
            {"dialog.apply_station_list_before_save", "保存する前に駅定義テーブルの変更を適用してください。"},
            {"dialog.open_document_unsaved_title", "ファイルを開く"}, {"dialog.open_document_unsaved_message", "未保存の変更があります。別のファイルを開いて変更を破棄しますか？"},
            {"about.text", "komapedit\nVersion 0.7.9\nCopyright © 2026 Sapporo_ningyo\nkobushi-trackviewer に基づく\nCopyright © 2021-2024 konawasabi\nLicense: Apache License 2.0\nThird-party: Dear ImGui (MIT), ImPlot (MIT)\nSee LICENSE, NOTICE, and THIRD_PARTY_NOTICES.md"}
        };
    }

    const std::string& get(Language lang, std::string_view key) const {
        const auto* table = &en;
        if (lang == Language::Zh) table = &zh;
        else if (lang == Language::Ja) table = &ja;
        auto it = table->find(key);
        if (it != table->end()) return it->second;
        auto it_en = en.find(key);
        if (it_en != en.end()) return it_en->second;
        static thread_local std::string missing;
        missing.assign(key.data(), key.size());
        return missing;
    }
};
