/*
 * Copyright (c) 2026 Sapporo_ningyo
 *
 * Licensed under Apache License 2.0; see LICENSE and NOTICE.
 */

#pragma once

#include <map>
#include <string>
#include <string_view>

enum class Language { Ja, En, Zh };

struct Translation {
    std::map<std::string, std::string, std::less<>> en;
    std::map<std::string, std::string, std::less<>> zh;
    std::map<std::string, std::string, std::less<>> ja;

    Translation() {
        en = {
            {"dialog.repeater_begin0_convert_title", "Convert Begin0"},
            {"dialog.repeater_begin0_convert_message", "This Repeater uses Begin0, so its coordinates cannot be edited directly. Convert it to Begin?"},
            {"label.repeater_end_source", "End source:"},
            {"label.repeater_structure_keys", "Structure keys"},
            {"status.repeater_multiple_begins", "This Repeater has multiple Begin statements."},
            {"status.repeater_no_end", "End position is empty because this Repeater has no End statement."},
            {"status.map_loading", "Loading map..."}, {"status.map_loaded", "Map loaded"}, {"status.map_load_failed", "Map load failed"},
            {"status.scene_preview_loading", "Loading 3D scene preview..."}, {"status.scene_preview_loaded", "3D scene preview loaded"}, {"status.scene_preview_failed", "3D scene preview failed"}, {"status.scene_preview_stopped", "3D scene preview stopped"},
            {"status.no_errors_warnings", "No errors or warnings"}, {"frame.errors_warnings", "Errors and Warnings"},
            {"scene.route_info.straight", "Straight"}, {"scene.route_info.interpolate_unsupported", "interpolate(unsupported)"}, {"scene.route_info.next_station", "Next sta. :"}, {"scene.route_info.no_station_ahead", "No station ahead"},
            {"dialog.distance_expression_message", "Edit the distance source expression manually?"},
            {"dialog.structure_put0_convert_title", "Convert Put0"}, {"dialog.structure_put0_convert_message", "This Structure uses Put0, so its coordinates cannot be edited directly. Convert it to Put?"},
            {"dialog.structure_z_rebase_title", "Adjust Distance"}, {"dialog.structure_z_rebase_message", "The current model's Z-axis offset exceeds 5 m. Adjust the distance?"},
            {"app.title", "komapedit"},
            {"menu.map_info.other_trains", "Other Train"},
            {"frame.other_trains", "Other Train List"},
            {"frame.other_train_definitions", "Definitions"},
            {"frame.other_train_stops", "Stop Points"},
            {"frame.structure_put", "Put"},
            {"frame.structure_put_between", "PutBetween"},
            {"menu.locate_in_other_train_stop_list", "Locate in Other Train Stop Point List"},
            {"frame.map_sounds", "Map Sound List"},
            {"frame.map_sound_3d", "Fixed Sound Source List"},
            {"button.map_sound_list", "Map Sound List"},
            {"button.map_sound_3d_list", "Map 3D Sound List"},
            {"chk.map_sound_markers", "Sound Play Positions"},
            {"chk.map_sound_3d_markers", "Fixed Sound Positions"},
            {"menu.locate_in_map_sound_list", "Locate in Map Sound List"},
            {"menu.locate_in_map_sound_3d_list", "Locate in Map 3D Sound List"},
            {"frame.rolling_noises", "Rolling Noise Change Point List"},
            {"chk.rolling_noise_markers", "Rolling Noise Change Points"},
            {"menu.locate_in_rolling_noise_list", "Locate in Rolling Noise Change Point List"},
            {"frame.flange_noises", "Flange Noise Change Point List"},
            {"chk.flange_noise_markers", "Flange Noise Change Points"},
            {"menu.locate_in_flange_noise_list", "Locate in Flange Noise Change Point List"},
            {"frame.joint_noises", "Joint Noise Play Point List"},
            {"chk.joint_noise_markers", "Joint Noise Play Points"},
            {"menu.locate_in_joint_noise_list", "Locate in Joint Noise Play Point List"},
            {"frame.backgrounds", "Background Change Point List"},
            {"chk.background_markers", "Background Change Points"},
            {"menu.locate_in_background_list", "Locate in Background Change Point List"},
            {"menu.file", "File"}, {"menu.options", "Options"}, {"menu.map_info", "Map Info List"}, {"menu.view_2d", "2D View"}, {"menu.lang", "Language"}, {"menu.help", "Help"},
            {"menu.map_info.othertracks", "Other Tracks"}, {"menu.map_info.station", "Station List"}, {"menu.map_info.signal_aspects", "Signal Aspect"}, {"menu.map_info.signals", "Map Signal"}, {"menu.map_info.beacons", "Beacon"},
            {"menu.map_info.structures", "Map Structure"}, {"menu.map_info.structures_put_between", "Map Structure (PutBetween)"}, {"menu.map_info.structure_models", "Structure Model"}, {"menu.map_info.sound_files", "Sound File"}, {"menu.map_info.sound_3d_files", "3D Sound File"}, {"menu.map_info.map_sounds", "Map Sound"},
            {"menu.map_info.map_sound_3d", "Map 3D Sound"}, {"menu.map_info.repeaters", "Repeater"}, {"menu.map_info.irregularities", "Track Irregularity"}, {"menu.map_info.rolling_noises", "Rolling Noise Change Point"}, {"menu.map_info.flange_noises", "Flange Noise Change Point"},
            {"menu.map_info.joint_noises", "Joint Noise Play Point"}, {"menu.map_info.backgrounds", "Background Change Point"}, {"menu.map_info.adhesions", "Adhesion Change Point"}, {"menu.map_info.cab_illuminance", "Cab Illuminance Change Point"}, {"menu.map_info.fogs", "Fog Change Point"}, {"menu.map_info.draw_distances", "Draw Distance Change Point"},
            {"menu.open", "Open..."}, {"menu.recent_maps", "Recent Maps"}, {"menu.none", "None"}, {"menu.clear_recent_maps", "Clear List"}, {"menu.reload", "Reload"}, {"menu.export_csv", "Export CSV..."}, {"menu.exit", "Exit"},
            {"menu.controlpoints", "Control Points..."}, {"menu.plotlimit", "Plot Range..."}, {"menu.ui_settings", "UI Settings..."}, {"menu.font_size", "UI Settings..."}, {"menu.canvas_2d_settings", "2D Canvas Settings"}, {"menu.canvas_element_sizes", "Canvas Element Sizes"}, {"menu.canvas_3d_settings", "3D Canvas Settings"}, {"menu.about", "About"},
            {"menu.online_docs", "Online Documentation"}, {"menu.report_bugs", "Report Bugs"}, {"menu.open_in_explorer", "Open in File Explorer"}, {"menu.preview_text", "Preview Text"}, {"menu.locate_on_plan", "Locate on Plan"}, {"menu.locate_in_scene_preview", "Locate in 3D Scene Preview"}, {"menu.locate_in_structure_list", "Locate in Map Structure List"}, {"menu.locate_in_structure_put_between_list", "Locate in Map Structure List (PutBetween)"}, {"menu.locate_in_repeater_list", "Locate in Repeater List"}, {"menu.repeater_delete_all", "Delete All"}, {"menu.repeater_delete_change_point", "Delete Change Point"}, {"menu.repeater_trim_to_change_point", "Trim to Change Point"}, {"menu.repeater_start_from_change_point", "Start from Change Point"}, {"menu.jump_to_repeater_start_position", "Jump to Start Position"}, {"menu.jump_to_repeater_end_or_change_position", "Jump to End/Change Position"}, {"menu.locate_in_signal_list", "Locate in Map Signal List"}, {"menu.locate_in_beacon_list", "Locate in Beacon List"}, {"menu.locate_in_irregularity_list", "Locate in Track Irregularity List"}, {"menu.locate_in_adhesion_list", "Locate in Adhesion Change Point List"}, {"menu.locate_in_cab_illuminance_list", "Locate in Cab Illuminance Change Point List"}, {"menu.locate_in_fog_list", "Locate in Fog Change Point List"}, {"menu.locate_in_draw_distance_list", "Locate in Draw Distance Change Point List"},
            {"menu.view_3d", "3D View"}, {"menu.structure_model_preview", "Structure Model Preview"}, {"menu.scene_preview", "3D Scene Preview"}, {"menu.preview_model", "Preview Model"}, {"menu.switch_signal_aspect", "Switch Signal Aspect"}, {"menu.find_in_structure_models", "Find in Structure Model List"}, {"menu.find_in_signal_aspects", "Find in Signal Aspect List"}, {"menu.find_in_sound_files", "Find in Sound File List"}, {"menu.find_in_sound_3d_files", "Find in 3D Sound File List"},
            {"button.open", "Open"}, {"button.reload", "Reload"}, {"button.reload_geometry", "Reload Track Geometry"}, {"button.reload_scene_models", "Reload (Models)"}, {"button.export_csv", "Export CSV"},
            {"button.structure_list", "Map Structure List"}, {"button.repeater_list", "Repeater List"},
            {"button.apply", "Apply"}, {"button.reset", "Reset"}, {"button.revert", "Revert"}, {"button.save", "Save"}, {"button.delete", "Delete"}, {"button.ok", "OK"}, {"button.cancel", "Cancel"}, {"button.clear", "Clear"}, {"button.copy", "Copy"}, {"button.close", "Close"}, {"button.previous", "Previous"}, {"button.next", "Next"}, {"button.confirm_reuse", "Reuse Anyway"}, {"button.manual_select", "Select Manually"},
            {"button.save_changes_and_exit", "Save Changes and Exit"}, {"button.discard_changes_and_exit", "Discard Changes and Exit"}, {"button.save_changes_and_close_edit", "Save Changes and Close Editing"}, {"button.discard_changes_and_close_edit", "Discard Changes and Close Editing"},
            {"button.model_list", "Model List"}, {"button.start_scene_preview", "Start 3D Scene Preview"}, {"button.background_color", "Background Color"}, {"button.find", "Find"}, {"button.find_unused_structure_models", "Search unused structure models"}, {"button.find_unused_signal_aspects", "Search unused signal aspects"}, {"button.find_unused_sound_files", "Search unused sounds"}, {"button.find_unused_sound_3d_files", "Search unused 3D sounds"},
            {"button.import_bg", "Import"}, {"button.adjust_bg", "Adjust"}, {"button.align_to_station", "Align to Station"}, {"button.jump", "Jump"},
            {"frame.controls", "Controls"}, {"frame.console", "Console"}, {"frame.file_structure_diagram", "File Structure Diagram"}, {"frame.text_preview", "Text Preview"}, {"frame.plots", "2D View"}, {"frame.othertracks", "Other Tracks"}, {"frame.station_list", "Station List"}, {"frame.station_positions", "Station Positions"}, {"frame.station_definitions", "Station Definitions"},
            {"frame.structures", "Map Structure List"}, {"frame.structures_put_between", "Map Structure List (PutBetween)"}, {"frame.structure_models", "Structure Model List"}, {"frame.sound_list", "Sound File List"}, {"frame.sound_3d_list", "3D Sound File List"}, {"frame.repeaters", "Repeater List"}, {"frame.signal_aspects", "Signal Aspect List"}, {"frame.signals", "Map Signal List"}, {"frame.beacons", "Beacon List"}, {"frame.irregularities", "Track Irregularity List"}, {"frame.adhesions", "Adhesion Change Point List"}, {"frame.cab_illuminance", "Cab Illuminance Change Point List"}, {"frame.fogs", "Fog Change Point List"}, {"frame.draw_distances", "Draw Distance Change Point List"}, {"frame.aux_info", "Auxiliary Info"}, {"frame.model_preview", "3D-Model Preview"}, {"frame.scene_preview", "3D-Scene Preview"},
            {"frame.chart_visibility", "Chart Visibility"}, {"frame.grid", "Grid"}, {"frame.mode", "Mode"}, {"frame.bgimage", "Background Image"},
            {"aux.station", "Station"}, {"aux.scenery", "Structures"}, {"aux.track_geometry", "Track Geometry"}, {"aux.signal", "Signal"}, {"aux.sound", "Sound"}, {"aux.effects", "Effects"}, {"aux.scene_3d", "3D Scene"}, {"aux.other", "Other"},
            {"column.file_name", "File Name"}, {"column.show", "Show"},
            {"find.partial_match", "Partial Match"}, {"find.exact_match", "Exact Match"},
            {"chk.station_pos", "Station Position"}, {"chk.station_name", "Station Name"}, {"chk.station_mileage", "Station Mileage"},
            {"chk.gradient_pos", "Gradient Change Points"}, {"chk.gradient_val", "Gradient Values"}, {"chk.curve_val", "Curve Radius"},
            {"chk.prof_othert", "Other Tracks (Profile)"}, {"chk.speedlimit", "Speed Limit"}, {"chk.irregularity_markers", "Track Irregularity Change Points"}, {"chk.beacon_markers", "Beacon Positions"}, {"chk.pretrain_markers", "PreTrain Pass Points"}, {"chk.other_train_paths", "Other Train Paths"}, {"chk.adhesion_markers", "Adhesion Change Points"}, {"chk.cab_illuminance_markers", "Cab Illuminance Change Points"}, {"chk.fog_markers", "Fog Change Points"}, {"chk.draw_distance_markers", "Draw Distance Change Points"}, {"chk.scene_owntrack_markers", "Own Track Markers"}, {"chk.scene_current_position_on_plan", "Show Current Position on Plan"}, {"chk.console_window", "Console Window"},
            {"chk.view_2d_window", "2D View Window"}, {"chk.select_all", "Select All"}, {"chk.edit_mode", "Enable Edit"},
            {"chk.edit_mode_warning_dont_show", "Don't show again"},
            {"chk.gradient_graph", "Profile"}, {"chk.curve_graph", "Radius"}, {"chk.bgimg_show", "Show"},
            {"grid.fixed", "Fixed"}, {"grid.movable", "Movable"}, {"grid.none", "None"},
            {"mode.pan", "Move"}, {"mode.select", "Select"}, {"mode.measure", "Measure"}, {"label.station_jump", "Station Jump"}, {"label.distance_jump", "Jump to distance(m)"}, {"label.source_file", "Source"}, {"label.source_position", "Position"}, {"label.source_distance_string", "Source Distance String"}, {"label.raw_statement", "Raw statement"}, {"label.source_section", "Source section"}, {"label.include_context", "Include context"}, {"label.pending_insertion", "Statement to insert"},
            {"canvas.plan", "Plan"}, {"canvas.profile", "Gradient / Height"}, {"canvas.radius", "Curve Radius"},
            {"plot.profile", "Profile"}, {"plot.radius", "Curve Radius"}, {"plot.level", "Level"}, {"unit.m", "m"},
            {"info.mileage", "Mileage"}, {"info.elevation", "Elevation"}, {"info.gradient", "Gradient"}, {"info.radius", "Curve Radius"},
            {"info.speedlimit", "Speed Limit"}, {"info.no_limit", "None"},
            {"hint.pick_bg_station", "Double-click the station position on the background image"}, {"hint.distance_choose_boundary", "Choose one of the parser-confirmed statement boundaries highlighted below."},
            {"label.bgimg_x", "X (m)"}, {"label.bgimg_y", "Y (m)"}, {"label.bgimg_width", "Width (m)"},
            {"label.bgimg_height", "Height (m)"}, {"label.bgimg_rotation", "Rotation (deg)"}, {"label.bgimg_brightness", "Brightness (%)"},
            {"label.font_size", "Text size"}, {"label.ui_component_size", "UI component size"}, {"label.station_marker_size", "Marker size"}, {"label.own_track_line_width", "Own track line width"}, {"label.other_track_line_width", "Other track line width"}, {"label.chart_marker_line_width", "Chart marker line width"}, {"label.background_grid_line_width", "Background grid line width"}, {"label.scene_fog_effect", "Fog effect"}, {"label.scene_map_draw_distance", "Adjust draw distance from map statements"}, {"label.scene_draw_distance", "Draw distance"}, {"label.scene_edit_component_size", "Edit component size"}, {"label.scene_camera_speed", "Camera movement speed"}, {"label.ui_theme_color", "Interface theme color"},
            {"label.font_size_current", "Text size:"}, {"label.ui_component_size_current", "Component size:"}, {"label.ui_theme_color_current", "Theme color:"}, {"label.font_size_preview", "Preview text"},
            {"label.quick_colors", "Quick colors"}, {"color.white", "White"}, {"color.black", "Black"}, {"color.gray", "Gray"}, {"color.blue", "Blue"}, {"color.green", "Green"},
            {"status.no_map", "No map loaded"}, {"status.loading", "Loading..."}, {"status.scene_loading", "Loading..."}, {"status.ready", "Ready"}, {"status.text_preview_load_failed", "Unable to load text preview."}, {"status.distance_no_boundaries", "No selectable statement boundary was returned."}, {"status.edit.pending", "Pending change"}, {"status.edit.pending_delete", "Pending delete"}, {"status.edit.reverted", "Reverted"}, {"status.edit.no_changes", "No changes"}, {"status.edit.required_field", "Required field is empty"}, {"status.edit.invalid_number", "Invalid number"}, {"status.edit.applied_to_preview", "Applied to preview"}, {"status.edit.saved", "Saved"}, {"status.edit.mode_enabled", "Edit mode enabled"}, {"status.edit.mode_disabled", "Edit mode disabled"}, {"status.edit.loading_metadata", "Loading edit metadata..."}, {"status.edit.disable_blocked_unsaved", "Save or revert pending edits before disabling edit mode."}, {"status.edit.distance_resolution_required", "A source placement choice is required"}, {"status.edit.distance_resolution_cancelled", "Source placement selection cancelled"},
            {"status.find.no_match", "No matching text found"}, {"status.find.match", "Found ({current}/{total})"}, {"status.unused_structure_models.match", "Found unused models ({unused}/{total})"}, {"status.unused_structure_models.no_match", "No unused models found"}, {"status.unused_signal_aspects.match", "Found unused signal aspects ({unused}/{total})"}, {"status.unused_signal_aspects.no_match", "No unused signal aspects found"}, {"status.unused_sound_files.match", "Found unused sounds ({unused}/{total})"}, {"status.unused_sound_files.no_match", "No unused sounds found"}, {"status.unused_sound_3d_files.match", "Found unused 3D sounds ({unused}/{total})"}, {"status.unused_sound_3d_files.no_match", "No unused 3D sounds found"},
            {"dialog.edit_mode_warning_title", "Enable Edit Mode"},
            {"dialog.edit_mode_warning_message", "Do you want to enable edit mode?\nEditing is an unstable, experimental feature and may make destructive changes to map files. Back up your map files first, or manage them with version control such as Git."},
            {"dialog.ui_settings", "UI Settings"}, {"dialog.canvas_element_sizes", "Canvas Element Sizes"}, {"dialog.canvas_3d_settings", "3D Canvas Settings"}, {"dialog.element_properties", "Properties/Edit"}, {"dialog.distance_resolution_title", "Distance Placement"}, {"dialog.distance_resolution_message", "Unable to determine where to move the statement automatically. Select manually?"}, {"dialog.distance_expression_title", "Distance Expression"}, {"dialog.distance_variable_message", "Variable [{variable}] has multiple values in this context. Edit the source expression manually?"}, {"dialog.reload_unsaved_title", "Reload from Disk"}, {"dialog.reload_unsaved_message", "There are unsaved changes. Reload from disk?"}, {"dialog.revert_all_edits_title", "Revert All Changes"}, {"dialog.revert_all_edits_message", "Revert all unsaved changes? This restores the in-memory map to its last saved state. This action cannot be redone."}, {"dialog.unsaved_changes_title", "Unsaved Changes"}, {"dialog.unsaved_exit_message", "There are unsaved changes. Are you sure you want to exit?"}, {"dialog.unsaved_close_edit_message", "There are unsaved changes. Are you sure you want to close editing?"}, {"dialog.bgimage_adjust", "Adjust Background Image"}, {"dialog.align_to_station", "Align Background to Stations"}, {"button.pick_on_bg", "Pick station on Plan"}, {"button.pick_on_bg_ok", "Picked"},
            {"about.text", "komapedit\nVersion 0.7.0\nCopyright © 2026 Sapporo_ningyo\nBased on kobushi-trackviewer\nCopyright © 2021-2024 konawasabi\nLicense: Apache License 2.0\nThird-party: Dear ImGui (MIT), ImPlot (MIT)\nSee LICENSE, NOTICE, and THIRD_PARTY_NOTICES.md"}
        };
        zh = {
            {"dialog.repeater_begin0_convert_title", "转换 Begin0"},
            {"dialog.repeater_begin0_convert_message", "此 Repeater 使用 Begin0，无法直接编辑坐标。是否转换为 Begin？"},
            {"label.repeater_end_source", "结束位置源："},
            {"label.repeater_structure_keys", "结构键列表"},
            {"status.repeater_multiple_begins", "此Repeater存在多个Begin语句"},
            {"status.repeater_no_end", "此 Repeater 没有 End 语句，因此结束位置留空。"},
            {"status.map_loading", "正在加载地图..."}, {"status.map_loaded", "地图加载完成"}, {"status.map_load_failed", "地图加载失败"},
            {"status.scene_preview_loading", "正在加载3D场景预览..."}, {"status.scene_preview_loaded", "3D场景预览已加载"}, {"status.scene_preview_failed", "3D场景预览加载失败"}, {"status.scene_preview_stopped", "3D场景预览已停止"},
            {"status.no_errors_warnings", "没有错误或警告"}, {"frame.errors_warnings", "错误与警告"},
            {"scene.route_info.straight", "Straight"}, {"scene.route_info.interpolate_unsupported", "interpolate(unsupported)"}, {"scene.route_info.next_station", "Next sta. :"}, {"scene.route_info.no_station_ahead", "No station ahead"},
            {"dialog.distance_expression_message", "是否手动编辑距离源字符串？"},
            {"dialog.structure_put0_convert_title", "转换 Put0"}, {"dialog.structure_put0_convert_message", "当前structure使用put0方法，无法直接编辑坐标，是否转换为Put？"},
            {"dialog.structure_z_rebase_title", "重新设置里程"}, {"dialog.structure_z_rebase_message", "当前模型的z轴偏移大于5m，是否重新设置里程？"},
            {"app.title", "komapedit"},
            {"menu.map_info.other_trains", "他列车"},
            {"frame.other_trains", "他列车列表"},
            {"frame.other_train_definitions", "定义"},
            {"frame.other_train_stops", "停止位置"},
            {"frame.structure_put", "Put"},
            {"frame.structure_put_between", "PutBetween"},
            {"menu.locate_in_other_train_stop_list", "定位至他列车停止位置列表"},
            {"frame.map_sounds", "地图音效列表"},
            {"frame.map_sound_3d", "固定音源音效"},
            {"button.map_sound_list", "地图音效列表"},
            {"button.map_sound_3d_list", "地图3D音效列表"},
            {"chk.map_sound_markers", "音效播放位置"},
            {"chk.map_sound_3d_markers", "固定音效位置"},
            {"menu.locate_in_map_sound_list", "定位至地图音效列表"},
            {"menu.locate_in_map_sound_3d_list", "定位至地图3D音效列表"},
            {"frame.rolling_noises", "走行音变化点列表"},
            {"chk.rolling_noise_markers", "走行音变化点"},
            {"menu.locate_in_rolling_noise_list", "定位至走行音变化点列表"},
            {"frame.flange_noises", "轮缘摩擦音效变化点列表"},
            {"chk.flange_noise_markers", "轮缘摩擦音效变化点"},
            {"menu.locate_in_flange_noise_list", "定位至轮缘摩擦音效变化点列表"},
            {"frame.joint_noises", "道岔音效播放点列表"},
            {"chk.joint_noise_markers", "道岔音效播放点"},
            {"menu.locate_in_joint_noise_list", "定位至道岔音效播放点列表"},
            {"frame.backgrounds", "背景变化点列表"},
            {"chk.background_markers", "背景变化点"},
            {"menu.locate_in_background_list", "定位至背景变化点列表"},
            {"menu.file", "文件"}, {"menu.options", "选项"}, {"menu.map_info", "地图信息列表"}, {"menu.view_2d", "2D视图"}, {"menu.lang", "语言"}, {"menu.help", "帮助"},
            {"menu.map_info.othertracks", "其他轨道"}, {"menu.map_info.station", "车站列表"}, {"menu.map_info.signal_aspects", "信号现示"}, {"menu.map_info.signals", "地图信号"}, {"menu.map_info.beacons", "应答器"},
            {"menu.map_info.structures", "地图布景"}, {"menu.map_info.structures_put_between", "地图布景(Putbetween)"}, {"menu.map_info.structure_models", "布景模型"}, {"menu.map_info.sound_files", "音效文件"}, {"menu.map_info.sound_3d_files", "3D音效文件"}, {"menu.map_info.map_sounds", "地图音效"},
            {"menu.map_info.map_sound_3d", "地图3D音效"}, {"menu.map_info.repeaters", "连续布景"}, {"menu.map_info.irregularities", "轨道变位"}, {"menu.map_info.rolling_noises", "走行音变化点"}, {"menu.map_info.flange_noises", "轮缘摩擦音效变化点"},
            {"menu.map_info.joint_noises", "道岔音效播放点"}, {"menu.map_info.backgrounds", "背景变化点"}, {"menu.map_info.adhesions", "粘着特性变化点"}, {"menu.map_info.cab_illuminance", "驾驶台亮度变化点"}, {"menu.map_info.fogs", "雾效果变化点"}, {"menu.map_info.draw_distances", "绘制距离变化点"},
            {"menu.open", "打开..."}, {"menu.recent_maps", "最近打开的地图"}, {"menu.none", "无"}, {"menu.clear_recent_maps", "清除列表"}, {"menu.reload", "重新加载"}, {"menu.export_csv", "导出 CSV..."}, {"menu.exit", "退出"},
            {"menu.controlpoints", "控制点间隔..."}, {"menu.plotlimit", "绘图范围..."}, {"menu.ui_settings", "用户界面设置..."}, {"menu.font_size", "用户界面设置..."}, {"menu.canvas_2d_settings", "2D画布设置"}, {"menu.canvas_element_sizes", "画布元素尺寸"}, {"menu.canvas_3d_settings", "3D画布设置"}, {"menu.about", "关于"},
            {"menu.online_docs", "在线文档"}, {"menu.report_bugs", "报告问题"}, {"menu.open_in_explorer", "在文件资源管理器中打开"}, {"menu.preview_text", "预览文本"}, {"menu.locate_on_plan", "定位至平面图"}, {"menu.locate_in_scene_preview", "定位至3D场景预览"}, {"menu.locate_in_structure_list", "定位至地图布景列表"}, {"menu.locate_in_structure_put_between_list", "定位至地图布景列表(Putbetween)"}, {"menu.locate_in_repeater_list", "定位至连续布景列表"}, {"menu.repeater_delete_all", "全部删除"}, {"menu.repeater_delete_change_point", "删除对应变化点"}, {"menu.repeater_trim_to_change_point", "修剪至变化点"}, {"menu.repeater_start_from_change_point", "从变化点开始"}, {"menu.jump_to_repeater_start_position", "跳至起始位置"}, {"menu.jump_to_repeater_end_or_change_position", "跳至结束/变化位置"}, {"menu.locate_in_signal_list", "定位至地图信号列表"}, {"menu.locate_in_beacon_list", "定位至应答器列表"}, {"menu.locate_in_irregularity_list", "定位至轨道变位列表"}, {"menu.locate_in_adhesion_list", "定位至粘着特性变化点列表"}, {"menu.locate_in_cab_illuminance_list", "定位至驾驶台亮度变化点列表"}, {"menu.locate_in_fog_list", "定位至雾效果变化点列表"}, {"menu.locate_in_draw_distance_list", "定位至绘制距离变化点列表"},
            {"menu.view_3d", "3D视图"}, {"menu.structure_model_preview", "布景模型预览"}, {"menu.scene_preview", "3D场景预览"}, {"menu.preview_model", "预览模型"}, {"menu.switch_signal_aspect", "切换信号现示"}, {"menu.find_in_structure_models", "在布景模型列表中查找"}, {"menu.find_in_signal_aspects", "在信号现示列表中查找"}, {"menu.find_in_sound_files", "在音效文件列表中查找"}, {"menu.find_in_sound_3d_files", "在3D音效文件列表中查找"},
            {"button.open", "打开"}, {"button.reload", "重新加载"}, {"button.reload_geometry", "重新加载线形"}, {"button.reload_scene_models", "重新加载（模型）"}, {"button.export_csv", "导出 CSV"},
            {"button.structure_list", "地图布景列表"}, {"button.repeater_list", "连续布景列表"},
            {"button.apply", "应用"}, {"button.reset", "重置"}, {"button.revert", "撤销"}, {"button.save", "保存"}, {"button.delete", "删除"}, {"button.ok", "确定"}, {"button.cancel", "取消"}, {"button.clear", "清除"}, {"button.copy", "复制"}, {"button.close", "关闭"}, {"button.previous", "上一个"}, {"button.next", "下一个"}, {"button.confirm_reuse", "仍然复用"}, {"button.manual_select", "手动选择"},
            {"button.save_changes_and_exit", "保存更改并退出"}, {"button.discard_changes_and_exit", "放弃更改并退出"}, {"button.save_changes_and_close_edit", "保存更改并关闭编辑"}, {"button.discard_changes_and_close_edit", "放弃更改并关闭编辑"},
            {"button.model_list", "模型列表"}, {"button.start_scene_preview", "启动3D场景预览"}, {"button.background_color", "背景颜色"}, {"button.find", "查找"}, {"button.find_unused_structure_models", "查找未使用布景模型"}, {"button.find_unused_signal_aspects", "查找未使用信号现示"}, {"button.find_unused_sound_files", "查找未使用音效"}, {"button.find_unused_sound_3d_files", "查找未使用3D音效"},
            {"button.import_bg", "导入"}, {"button.adjust_bg", "调整"}, {"button.align_to_station", "按车站对齐"}, {"button.jump", "跳转"},
            {"frame.controls", "控制"}, {"frame.console", "控制台"}, {"frame.file_structure_diagram", "文件结构图"}, {"frame.text_preview", "文本预览"}, {"frame.plots", "2D视图"}, {"frame.othertracks", "其他轨道"}, {"frame.station_list", "车站列表"}, {"frame.station_positions", "车站位置"}, {"frame.station_definitions", "车站定义"},
            {"frame.structures", "地图布景列表"}, {"frame.structures_put_between", "地图布景列表(Putbetween)"}, {"frame.structure_models", "布景模型列表"}, {"frame.sound_list", "音效文件列表"}, {"frame.sound_3d_list", "3D音效文件列表"}, {"frame.repeaters", "连续布景列表"}, {"frame.signal_aspects", "信号现示列表"}, {"frame.signals", "地图信号列表"}, {"frame.beacons", "应答器列表"}, {"frame.irregularities", "轨道变位列表"}, {"frame.adhesions", "粘着特性变化点列表"}, {"frame.cab_illuminance", "驾驶台亮度变化点列表"}, {"frame.fogs", "雾效果变化点列表"}, {"frame.draw_distances", "绘制距离变化点列表"}, {"frame.aux_info", "辅助信息"}, {"frame.model_preview", "3D-模型预览"}, {"frame.scene_preview", "3D-场景预览"},
            {"frame.chart_visibility", "图表显示"}, {"frame.grid", "网格"}, {"frame.mode", "模式"}, {"frame.bgimage", "背景图"},
            {"aux.station", "车站"}, {"aux.scenery", "布景"}, {"aux.track_geometry", "轨道几何"}, {"aux.signal", "信号"}, {"aux.sound", "音效"}, {"aux.effects", "效果"}, {"aux.scene_3d", "3D场景"}, {"aux.other", "其它"},
            {"column.file_name", "文件名"}, {"column.show", "显示"},
            {"find.partial_match", "部分匹配"}, {"find.exact_match", "完全匹配"},
            {"chk.station_pos", "车站位置"}, {"chk.station_name", "车站名"}, {"chk.station_mileage", "车站里程"},
            {"chk.gradient_pos", "坡度变化点"}, {"chk.gradient_val", "坡度值"}, {"chk.curve_val", "曲线半径"},
            {"chk.prof_othert", "纵断面其他轨道"}, {"chk.speedlimit", "限速"}, {"chk.irregularity_markers", "轨道变位变化点"}, {"chk.beacon_markers", "应答器位置"}, {"chk.pretrain_markers", "先行列车通过点"}, {"chk.other_train_paths", "他列车路径"}, {"chk.adhesion_markers", "粘着特性变化点"}, {"chk.cab_illuminance_markers", "驾驶台亮度变化点"}, {"chk.fog_markers", "雾效果变化点"}, {"chk.draw_distance_markers", "绘制距离变化点"}, {"chk.scene_owntrack_markers", "自轨道标记"}, {"chk.scene_current_position_on_plan", "平面图上显示当前位置"}, {"chk.console_window", "控制台窗口"},
            {"chk.view_2d_window", "2D视图窗口"}, {"chk.select_all", "全选"}, {"chk.edit_mode", "编辑模式"},
            {"chk.edit_mode_warning_dont_show", "不再显示"},
            {"chk.gradient_graph", "纵断面图"}, {"chk.curve_graph", "曲线半径图"}, {"chk.bgimg_show", "显示"},
            {"grid.fixed", "固定"}, {"grid.movable", "可移动"}, {"grid.none", "无"},
            {"mode.pan", "移动"}, {"mode.select", "选择"}, {"mode.measure", "测量"}, {"label.station_jump", "车站跳转"}, {"label.distance_jump", "跳转到里程(m)"}, {"label.source_file", "源文件"}, {"label.source_position", "位置"}, {"label.source_distance_string", "原始距离字符串"}, {"label.raw_statement", "原始语句"}, {"label.source_section", "源码区段"}, {"label.include_context", "Include 上下文"}, {"label.pending_insertion", "将要插入的语句"},
            {"canvas.plan", "平面图"}, {"canvas.profile", "纵断面 / 标高"}, {"canvas.radius", "曲线半径"},
            {"plot.profile", "纵断面"}, {"plot.radius", "曲线半径"}, {"plot.level", "水平"}, {"unit.m", "m"},
            {"info.mileage", "里程"}, {"info.elevation", "标高"}, {"info.gradient", "坡度"}, {"info.radius", "曲线半径"},
            {"info.speedlimit", "限速"}, {"info.no_limit", "无"},
            {"hint.pick_bg_station", "双击背景图上的车站位置"}, {"hint.distance_choose_boundary", "请选择下方由解析器确认并高亮的语句边界。"},
            {"label.bgimg_x", "X (m)"}, {"label.bgimg_y", "Y (m)"}, {"label.bgimg_width", "宽度 (m)"},
            {"label.bgimg_height", "高度 (m)"}, {"label.bgimg_rotation", "旋转角度 (度)"}, {"label.bgimg_brightness", "亮度 (%)"},
            {"label.font_size", "文字大小"}, {"label.ui_component_size", "界面组件大小"}, {"label.station_marker_size", "标记尺寸"}, {"label.own_track_line_width", "自轨道标线宽度"}, {"label.other_track_line_width", "他轨道标线宽度"}, {"label.chart_marker_line_width", "图表标线宽度"}, {"label.background_grid_line_width", "背景网格线宽度"}, {"label.scene_fog_effect", "雾效果"}, {"label.scene_map_draw_distance", "绘制距离根据地图语句调整"}, {"label.scene_draw_distance", "绘制距离"}, {"label.scene_edit_component_size", "编辑用组件尺寸"}, {"label.scene_camera_speed", "相机移动速度"}, {"label.ui_theme_color", "界面主题色"},
            {"label.font_size_current", "文字大小："}, {"label.ui_component_size_current", "组件大小："}, {"label.ui_theme_color_current", "主题色："}, {"label.font_size_preview", "预览文字"},
            {"label.quick_colors", "快捷颜色"}, {"color.white", "纯白"}, {"color.black", "纯黑"}, {"color.gray", "灰色"}, {"color.blue", "纯蓝色"}, {"color.green", "纯绿色"},
            {"status.no_map", "未加载地图"}, {"status.loading", "加载中..."}, {"status.scene_loading", "正在加载……"}, {"status.ready", "就绪"}, {"status.text_preview_load_failed", "无法加载文本预览。"}, {"status.distance_no_boundaries", "解析器未返回可选的语句边界。"}, {"status.edit.pending", "待保存更改"}, {"status.edit.pending_delete", "待删除"}, {"status.edit.reverted", "已撤销"}, {"status.edit.no_changes", "没有更改"}, {"status.edit.required_field", "必填项为空"}, {"status.edit.invalid_number", "数字无效"}, {"status.edit.applied_to_preview", "已应用到预览"}, {"status.edit.saved", "已保存"}, {"status.edit.mode_enabled", "编辑模式已启用"}, {"status.edit.mode_disabled", "编辑模式已关闭"}, {"status.edit.loading_metadata", "正在加载编辑元数据..."}, {"status.edit.disable_blocked_unsaved", "关闭编辑模式前请先保存或撤销待保存更改。"}, {"status.edit.distance_resolution_required", "需要选择源码插入位置"}, {"status.edit.distance_resolution_cancelled", "已取消源码插入位置选择"},
            {"status.find.no_match", "未找到匹配的字符"}, {"status.find.match", "查找到（{current}/{total}）"}, {"status.unused_structure_models.match", "找到未使用模型（{unused}/{total}）"}, {"status.unused_structure_models.no_match", "没有找到未使用模型"}, {"status.unused_signal_aspects.match", "找到未使用信号现示（{unused}/{total}）"}, {"status.unused_signal_aspects.no_match", "没有找到未使用信号现示"}, {"status.unused_sound_files.match", "找到未使用音效（{unused}/{total}）"}, {"status.unused_sound_files.no_match", "没有找到未使用音效"}, {"status.unused_sound_3d_files.match", "找到未使用3D音效（{unused}/{total}）"}, {"status.unused_sound_3d_files.no_match", "没有找到未使用3D音效"},
            {"dialog.edit_mode_warning_title", "启用编辑模式"},
            {"dialog.edit_mode_warning_message", "是否启用编辑模式？\n编辑属于不稳定的测试性功能，可能会对地图文件产生破坏性更改。建议事先备份地图文件，或使用 Git 等版本控制工具管理地图文件。"},
            {"dialog.ui_settings", "用户界面设置"}, {"dialog.canvas_element_sizes", "画布元素尺寸"}, {"dialog.canvas_3d_settings", "3D画布设置"}, {"dialog.element_properties", "属性/编辑"}, {"dialog.distance_resolution_title", "距离语句移动位置"}, {"dialog.distance_resolution_message", "无法自动确定语句移动位置，是否手动选择？"}, {"dialog.distance_expression_title", "距离源字符串"}, {"dialog.distance_variable_message", "变量[{variable}]在上下文中存在多个值，是否手动编辑源字符串？"}, {"dialog.reload_unsaved_title", "重新加载"}, {"dialog.reload_unsaved_message", "有未保存的更改，确认是否重新加载？"}, {"dialog.revert_all_edits_title", "撤销全部改动"}, {"dialog.revert_all_edits_message", "撤销所有未保存的改动吗？这会将内存中的地图恢复到上次保存后的状态，且无法重做。"}, {"dialog.unsaved_changes_title", "未保存的更改"}, {"dialog.unsaved_exit_message", "有未保存的更改，确定要退出吗？"}, {"dialog.unsaved_close_edit_message", "有未保存的更改，确定要关闭编辑吗？"}, {"dialog.bgimage_adjust", "调整背景图"}, {"dialog.align_to_station", "按车站对齐背景图"}, {"button.pick_on_bg", "在平面图选点"}, {"button.pick_on_bg_ok", "已选点"},
            {"about.text", "komapedit\nVersion 0.7.0\nCopyright © 2026 Sapporo_ningyo\n基于 kobushi-trackviewer\nCopyright © 2021-2024 konawasabi\n许可证：Apache License 2.0\n第三方：Dear ImGui (MIT)、ImPlot (MIT)\n详见 LICENSE、NOTICE 和 THIRD_PARTY_NOTICES.md"}
        };
        ja = {
            {"dialog.repeater_begin0_convert_title", "Begin0 の変換"},
            {"dialog.repeater_begin0_convert_message", "この Repeater は Begin0 を使用しているため、座標を直接編集できません。Begin に変換しますか？"},
            {"label.repeater_end_source", "終了位置のソース："},
            {"label.repeater_structure_keys", "構造物キー"},
            {"status.repeater_multiple_begins", "この Repeater には複数の Begin 文があります。"},
            {"status.repeater_no_end", "この Repeater には End 文がないため、終了位置は空です。"},
            {"status.map_loading", "マップを読み込み中..."}, {"status.map_loaded", "マップの読み込みが完了しました"}, {"status.map_load_failed", "マップの読み込みに失敗しました"},
            {"status.scene_preview_loading", "3Dシーンプレビューを読み込み中..."}, {"status.scene_preview_loaded", "3Dシーンプレビューの読み込みが完了しました"}, {"status.scene_preview_failed", "3Dシーンプレビューの読み込みに失敗しました"}, {"status.scene_preview_stopped", "3Dシーンプレビューを停止しました"},
            {"status.no_errors_warnings", "エラーまたは警告はありません"}, {"frame.errors_warnings", "エラーと警告"},
            {"scene.route_info.straight", "Straight"}, {"scene.route_info.interpolate_unsupported", "interpolate(unsupported)"}, {"scene.route_info.next_station", "Next sta. :"}, {"scene.route_info.no_station_ahead", "No station ahead"},
            {"dialog.distance_expression_message", "距離のソース文字列を手動で編集しますか？"},
            {"dialog.structure_put0_convert_title", "Put0 の変換"}, {"dialog.structure_put0_convert_message", "この Structure は Put0 を使用しているため、座標を直接編集できません。Put に変換しますか？"},
            {"dialog.structure_z_rebase_title", "距離の再設定"}, {"dialog.structure_z_rebase_message", "現在のモデルの Z 軸オフセットが 5 m を超えています。距離を再設定しますか？"},
            {"app.title", "komapedit"},
            {"menu.map_info.other_trains", "他列車"},
            {"frame.other_trains", "他列車リスト"},
            {"frame.other_train_definitions", "定義"},
            {"frame.other_train_stops", "停止位置"},
            {"frame.structure_put", "Put"},
            {"frame.structure_put_between", "PutBetween"},
            {"menu.locate_in_other_train_stop_list", "他列車停止位置リストへ移動"},
            {"frame.map_sounds", "マップサウンドリスト"},
            {"frame.map_sound_3d", "固定音源サウンド"},
            {"button.map_sound_list", "マップサウンドリスト"},
            {"button.map_sound_3d_list", "マップ3Dサウンドリスト"},
            {"chk.map_sound_markers", "サウンド再生位置"},
            {"chk.map_sound_3d_markers", "固定サウンド位置"},
            {"menu.locate_in_map_sound_list", "マップサウンドリストへ移動"},
            {"menu.locate_in_map_sound_3d_list", "マップ3Dサウンドリストへ移動"},
            {"frame.rolling_noises", "走行音変化点リスト"},
            {"chk.rolling_noise_markers", "走行音変化点"},
            {"menu.locate_in_rolling_noise_list", "走行音変化点リストへ移動"},
            {"frame.flange_noises", "フランジきしり音変化点リスト"},
            {"chk.flange_noise_markers", "フランジきしり音変化点"},
            {"menu.locate_in_flange_noise_list", "フランジきしり音変化点リストへ移動"},
            {"frame.joint_noises", "分岐器通過音再生点リスト"},
            {"chk.joint_noise_markers", "分岐器通過音再生点"},
            {"menu.locate_in_joint_noise_list", "分岐器通過音再生点リストへ移動"},
            {"frame.backgrounds", "背景変化点リスト"},
            {"chk.background_markers", "背景変化点"},
            {"menu.locate_in_background_list", "背景変化点リストへ移動"},
            {"menu.file", "ファイル"}, {"menu.options", "オプション"}, {"menu.map_info", "マップ情報リスト"}, {"menu.view_2d", "2Dプロット"}, {"menu.lang", "言語"}, {"menu.help", "ヘルプ"},
            {"menu.map_info.othertracks", "他軌道"}, {"menu.map_info.station", "停車場"}, {"menu.map_info.signal_aspects", "信号現示"}, {"menu.map_info.signals", "マップ信号"}, {"menu.map_info.beacons", "地上子"},
            {"menu.map_info.structures", "マップストラクチャー"}, {"menu.map_info.structures_put_between", "マップストラクチャー(PutBetween)"}, {"menu.map_info.structure_models", "ストラクチャーモデル"}, {"menu.map_info.sound_files", "サウンドファイル"}, {"menu.map_info.sound_3d_files", "3Dサウンドファイル"}, {"menu.map_info.map_sounds", "マップサウンド"},
            {"menu.map_info.map_sound_3d", "マップ3Dサウンド"}, {"menu.map_info.repeaters", "連続ストラクチャー"}, {"menu.map_info.irregularities", "軌道変位"}, {"menu.map_info.rolling_noises", "走行音変化点"}, {"menu.map_info.flange_noises", "フランジきしり音変化点"},
            {"menu.map_info.joint_noises", "分岐器通過音再生点"}, {"menu.map_info.backgrounds", "背景変化点"}, {"menu.map_info.adhesions", "粘着特性変化点"}, {"menu.map_info.cab_illuminance", "運転台明るさ変化点"}, {"menu.map_info.fogs", "霧効果変化点"}, {"menu.map_info.draw_distances", "描画距離変化点"},
            {"menu.open", "開く..."}, {"menu.recent_maps", "最近開いたマップ"}, {"menu.none", "なし"}, {"menu.clear_recent_maps", "リストをクリア"}, {"menu.reload", "再読込"}, {"menu.export_csv", "CSV 出力..."}, {"menu.exit", "終了"},
            {"menu.controlpoints", "制御点間隔..."}, {"menu.plotlimit", "描画範囲..."}, {"menu.ui_settings", "UI設定..."}, {"menu.font_size", "UI設定..."}, {"menu.canvas_2d_settings", "2Dキャンバス設定"}, {"menu.canvas_element_sizes", "キャンバス要素サイズ"}, {"menu.canvas_3d_settings", "3Dキャンバス設定"}, {"menu.about", "このアプリについて"},
            {"menu.online_docs", "オンラインドキュメント"}, {"menu.report_bugs", "不具合を報告"}, {"menu.open_in_explorer", "エクスプローラーで開く"}, {"menu.preview_text", "テキストをプレビュー"}, {"menu.locate_on_plan", "平面図へ移動"}, {"menu.locate_in_scene_preview", "3Dシーンプレビューへ移動"}, {"menu.locate_in_structure_list", "ストラクチャーリストへ移動"}, {"menu.locate_in_structure_put_between_list", "ストラクチャーリスト(PutBetween)へ移動"}, {"menu.locate_in_repeater_list", "連続ストラクチャーリストへ移動"}, {"menu.repeater_delete_all", "すべて削除"}, {"menu.repeater_delete_change_point", "対応する変化点を削除"}, {"menu.repeater_trim_to_change_point", "変化点までトリム"}, {"menu.repeater_start_from_change_point", "変化点から開始"}, {"menu.jump_to_repeater_start_position", "開始位置へジャンプ"}, {"menu.jump_to_repeater_end_or_change_position", "終了/変更位置へジャンプ"}, {"menu.locate_in_signal_list", "マップ信号リストへ移動"}, {"menu.locate_in_beacon_list", "地上子リストへ移動"}, {"menu.locate_in_irregularity_list", "軌道変位リストへ移動"}, {"menu.locate_in_adhesion_list", "粘着特性変化点リストへ移動"}, {"menu.locate_in_cab_illuminance_list", "運転台明るさ変化点リストへ移動"}, {"menu.locate_in_fog_list", "霧効果変化点リストへ移動"}, {"menu.locate_in_draw_distance_list", "描画距離変化点リストへ移動"},
            {"menu.view_3d", "3Dビュー"}, {"menu.structure_model_preview", "ストラクチャーモデルプレビュー"}, {"menu.scene_preview", "3Dシーンプレビュー"}, {"menu.preview_model", "モデルをプレビュー"}, {"menu.switch_signal_aspect", "信号現示を切替"}, {"menu.find_in_structure_models", "ストラクチャーモデルリストで検索"}, {"menu.find_in_signal_aspects", "信号現示リストで検索"}, {"menu.find_in_sound_files", "サウンドファイルリストで検索"}, {"menu.find_in_sound_3d_files", "3Dサウンドファイルリストで検索"},
            {"button.open", "開く"}, {"button.reload", "再読込"}, {"button.reload_geometry", "線形を再読込"}, {"button.reload_scene_models", "再読込（モデル）"}, {"button.export_csv", "CSV 出力"},
            {"button.structure_list", "マップストラクチャーリスト"}, {"button.repeater_list", "連続ストラクチャーリスト"},
            {"button.apply", "適用"}, {"button.reset", "リセット"}, {"button.revert", "元に戻す"}, {"button.save", "保存"}, {"button.delete", "削除"}, {"button.ok", "OK"}, {"button.cancel", "キャンセル"}, {"button.clear", "クリア"}, {"button.copy", "コピー"}, {"button.close", "閉じる"}, {"button.previous", "前へ"}, {"button.next", "次へ"}, {"button.confirm_reuse", "そのまま再利用"}, {"button.manual_select", "手動で選択"},
            {"button.save_changes_and_exit", "変更を保存して終了"}, {"button.discard_changes_and_exit", "変更を破棄して終了"}, {"button.save_changes_and_close_edit", "変更を保存して編集を終了"}, {"button.discard_changes_and_close_edit", "変更を破棄して編集を終了"},
            {"button.model_list", "モデルリスト"}, {"button.start_scene_preview", "3Dシーンプレビューを開始"}, {"button.background_color", "背景色"}, {"button.find", "検索"}, {"button.find_unused_structure_models", "未使用モデルを検索"}, {"button.find_unused_signal_aspects", "未使用信号現示を検索"}, {"button.find_unused_sound_files", "未使用サウンドを検索"}, {"button.find_unused_sound_3d_files", "未使用3Dサウンドを検索"},
            {"button.import_bg", "インポート"}, {"button.adjust_bg", "調整"}, {"button.align_to_station", "駅に合わせる"}, {"button.jump", "ジャンプ"},
            {"frame.controls", "コントロール"}, {"frame.console", "コンソール"}, {"frame.file_structure_diagram", "ファイル構成図"}, {"frame.text_preview", "テキストプレビュー"}, {"frame.plots", "2Dビュー"}, {"frame.othertracks", "他軌道"}, {"frame.station_list", "停車場リスト"}, {"frame.station_positions", "停車場位置"}, {"frame.station_definitions", "停車場定義"},
            {"frame.structures", "ストラクチャーリスト"}, {"frame.structures_put_between", "ストラクチャーリスト(PutBetween)"}, {"frame.structure_models", "ストラクチャーモデルリスト"}, {"frame.sound_list", "サウンドファイルリスト"}, {"frame.sound_3d_list", "3Dサウンドファイルリスト"}, {"frame.repeaters", "連続ストラクチャーリスト"}, {"frame.signal_aspects", "信号現示リスト"}, {"frame.signals", "マップ信号リスト"}, {"frame.beacons", "地上子リスト"}, {"frame.irregularities", "軌道変位リスト"}, {"frame.adhesions", "粘着特性変化点リスト"}, {"frame.cab_illuminance", "運転台明るさ変化点リスト"}, {"frame.fogs", "霧効果変化点リスト"}, {"frame.draw_distances", "描画距離変化点リスト"}, {"frame.aux_info", "補助情報"}, {"frame.model_preview", "3D-モデルプレビュー"}, {"frame.scene_preview", "3D-シーンプレビュー"},
            {"frame.chart_visibility", "チャート表示"}, {"frame.grid", "グリッド"}, {"frame.mode", "モード"}, {"frame.bgimage", "背景画像"},
            {"aux.station", "駅"}, {"aux.scenery", "ストラクチャー"}, {"aux.track_geometry", "軌道幾何"}, {"aux.signal", "信号"}, {"aux.sound", "サウンド"}, {"aux.effects", "効果"}, {"aux.scene_3d", "3Dシーン"}, {"aux.other", "その他"},
            {"column.file_name", "ファイル名"}, {"column.show", "表示"},
            {"find.partial_match", "部分一致"}, {"find.exact_match", "完全一致"},
            {"chk.station_pos", "駅位置"}, {"chk.station_name", "駅名"}, {"chk.station_mileage", "駅キロ程"},
            {"chk.gradient_pos", "勾配変化点"}, {"chk.gradient_val", "勾配値"}, {"chk.curve_val", "曲線半径"},
            {"chk.prof_othert", "縦断面の他軌道"}, {"chk.speedlimit", "速度制限"}, {"chk.irregularity_markers", "軌道変位変化点"}, {"chk.beacon_markers", "地上子位置"}, {"chk.pretrain_markers", "先行列車通過点"}, {"chk.other_train_paths", "他列車経路"}, {"chk.adhesion_markers", "粘着特性変化点"}, {"chk.cab_illuminance_markers", "運転台明るさ変化点"}, {"chk.fog_markers", "霧効果変化点"}, {"chk.draw_distance_markers", "描画距離変化点"}, {"chk.scene_owntrack_markers", "自軌道マーカー"}, {"chk.scene_current_position_on_plan", "平面図に現在位置を表示"}, {"chk.console_window", "コンソールウィンドウ"},
            {"chk.view_2d_window", "2Dビューウィンドウ"}, {"chk.select_all", "すべて選択"}, {"chk.edit_mode", "編集モード"},
            {"chk.edit_mode_warning_dont_show", "今後表示しない"},
            {"chk.gradient_graph", "縦断面図"}, {"chk.curve_graph", "曲線半径図"}, {"chk.bgimg_show", "表示"},
            {"grid.fixed", "固定"}, {"grid.movable", "可動"}, {"grid.none", "なし"},
            {"mode.pan", "移動"}, {"mode.select", "選択"}, {"mode.measure", "測定"}, {"label.station_jump", "駅ジャンプ"}, {"label.distance_jump", "距離へジャンプ(m)"}, {"label.source_file", "ソース"}, {"label.source_position", "位置"}, {"label.source_distance_string", "元の距離文字列"}, {"label.raw_statement", "元の文"}, {"label.source_section", "ソース区間"}, {"label.include_context", "Include コンテキスト"}, {"label.pending_insertion", "挿入する文"},
            {"canvas.plan", "平面図"}, {"canvas.profile", "縦断面 / 標高"}, {"canvas.radius", "曲線半径"},
            {"plot.profile", "縦断面"}, {"plot.radius", "曲線半径"}, {"plot.level", "水平"}, {"unit.m", "m"},
            {"info.mileage", "キロ程"}, {"info.elevation", "標高"}, {"info.gradient", "勾配"}, {"info.radius", "曲線半径"},
            {"info.speedlimit", "速度制限"}, {"info.no_limit", "なし"},
            {"hint.pick_bg_station", "背景画像上の駅位置をダブルクリック"}, {"hint.distance_choose_boundary", "下で強調表示された、パーサー確認済みの文境界を選択してください。"},
            {"label.bgimg_x", "X (m)"}, {"label.bgimg_y", "Y (m)"}, {"label.bgimg_width", "幅 (m)"},
            {"label.bgimg_height", "高さ (m)"}, {"label.bgimg_rotation", "回転角 (度)"}, {"label.bgimg_brightness", "明るさ (%)"},
            {"label.font_size", "文字サイズ"}, {"label.ui_component_size", "UI部品サイズ"}, {"label.station_marker_size", "マーカーサイズ"}, {"label.own_track_line_width", "自軌道ライン幅"}, {"label.other_track_line_width", "他軌道ライン幅"}, {"label.chart_marker_line_width", "チャートマーカー線幅"}, {"label.background_grid_line_width", "背景グリッド線幅"}, {"label.scene_fog_effect", "霧効果"}, {"label.scene_map_draw_distance", "マップ文に応じて描画距離を調整"}, {"label.scene_draw_distance", "描画距離"}, {"label.scene_edit_component_size", "編集用コンポーネントサイズ"}, {"label.scene_camera_speed", "カメラ移動速度"}, {"label.ui_theme_color", "UIテーマカラー"},
            {"label.font_size_current", "文字サイズ："}, {"label.ui_component_size_current", "部品サイズ："}, {"label.ui_theme_color_current", "テーマカラー："}, {"label.font_size_preview", "プレビューテキスト"},
            {"label.quick_colors", "クイック色"}, {"color.white", "白"}, {"color.black", "黒"}, {"color.gray", "グレー"}, {"color.blue", "青"}, {"color.green", "緑"},
            {"status.no_map", "地図が読み込まれていません"}, {"status.loading", "読込中..."}, {"status.scene_loading", "読み込み中..."}, {"status.ready", "準備完了"}, {"status.text_preview_load_failed", "テキストプレビューを読み込めませんでした。"}, {"status.distance_no_boundaries", "選択可能な文境界がパーサーから返されませんでした。"}, {"status.edit.pending", "未保存の変更"}, {"status.edit.pending_delete", "削除待ち"}, {"status.edit.reverted", "元に戻しました"}, {"status.edit.no_changes", "変更なし"}, {"status.edit.required_field", "必須項目が空です"}, {"status.edit.invalid_number", "数値が不正です"}, {"status.edit.applied_to_preview", "プレビューに適用しました"}, {"status.edit.saved", "保存しました"}, {"status.edit.mode_enabled", "編集モードを有効にしました"}, {"status.edit.mode_disabled", "編集モードを無効にしました"}, {"status.edit.loading_metadata", "編集メタデータを読み込み中..."}, {"status.edit.disable_blocked_unsaved", "編集モードを無効にする前に変更を保存または元に戻してください。"}, {"status.edit.distance_resolution_required", "ソースの挿入位置を選択してください"}, {"status.edit.distance_resolution_cancelled", "ソースの挿入位置選択をキャンセルしました"},
            {"status.find.no_match", "一致する文字が見つかりません"}, {"status.find.match", "検索結果（{current}/{total}）"}, {"status.unused_structure_models.match", "未使用モデルを検出（{unused}/{total}）"}, {"status.unused_structure_models.no_match", "未使用モデルは見つかりません"}, {"status.unused_signal_aspects.match", "未使用信号現示を検出（{unused}/{total}）"}, {"status.unused_signal_aspects.no_match", "未使用信号現示は見つかりません"}, {"status.unused_sound_files.match", "未使用サウンドを検出（{unused}/{total}）"}, {"status.unused_sound_files.no_match", "未使用サウンドは見つかりません"}, {"status.unused_sound_3d_files.match", "未使用3Dサウンドを検出（{unused}/{total}）"}, {"status.unused_sound_3d_files.no_match", "未使用3Dサウンドは見つかりません"},
            {"dialog.edit_mode_warning_title", "編集モードを有効化"},
            {"dialog.edit_mode_warning_message", "編集モードを有効にしますか？\n編集機能は不安定な実験的機能であり、マップファイルに破壊的な変更を加える可能性があります。事前にマップファイルをバックアップするか、Git などのバージョン管理ツールで管理することをお勧めします。"},
            {"dialog.ui_settings", "UI設定"}, {"dialog.canvas_element_sizes", "キャンバス要素サイズ"}, {"dialog.canvas_3d_settings", "3Dキャンバス設定"}, {"dialog.element_properties", "プロパティ/編集"}, {"dialog.distance_resolution_title", "距離文の移動位置"}, {"dialog.distance_resolution_message", "文の移動位置を自動で決定できません。手動で選択しますか？"}, {"dialog.distance_expression_title", "距離のソース文字列"}, {"dialog.distance_variable_message", "変数[{variable}]はコンテキスト内で複数の値を持ちます。ソース文字列を手動で編集しますか？"}, {"dialog.reload_unsaved_title", "再読込"}, {"dialog.reload_unsaved_message", "未保存の変更があります。再読込しますか？"}, {"dialog.revert_all_edits_title", "すべての変更を元に戻す"}, {"dialog.revert_all_edits_message", "未保存の変更をすべて元に戻しますか？メモリ上のマップを前回保存時の状態に戻します。この操作はやり直せません。"}, {"dialog.unsaved_changes_title", "未保存の変更"}, {"dialog.unsaved_exit_message", "未保存の変更があります。終了してもよろしいですか？"}, {"dialog.unsaved_close_edit_message", "未保存の変更があります。編集を終了してもよろしいですか？"}, {"dialog.bgimage_adjust", "背景画像の調整"}, {"dialog.align_to_station", "背景画像を駅に合わせる"}, {"button.pick_on_bg", "平面図で駅を選択"}, {"button.pick_on_bg_ok", "選択済み"},
            {"about.text", "komapedit\nVersion 0.7.0\nCopyright © 2026 Sapporo_ningyo\nkobushi-trackviewer に基づく\nCopyright © 2021-2024 konawasabi\nLicense: Apache License 2.0\nThird-party: Dear ImGui (MIT), ImPlot (MIT)\nSee LICENSE, NOTICE, and THIRD_PARTY_NOTICES.md"}
        };
    }

    const std::string& get(Language lang, std::string_view key) const {
        const auto* table = &en;
        if (lang == Language::Zh) table = &zh;
        else if (lang == Language::Ja) table = &ja;
        auto it = table->find(key);
        if (it != table->end()) return it->second;
        auto it_en = en.find(key);
        if (it_en != en.end()) return it_en->second;
        static thread_local std::string missing;
        missing.assign(key.data(), key.size());
        return missing;
    }
};
